"use client";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import type { C3ProgramDetail, DeploymentCommandType, DeploymentStatus } from "@/lib/server/research-c3/models";
import type { QualificationRecord } from "@/lib/server/research-c2/models";

async function post(programId:string,payload:Record<string,unknown>){const response=await fetch(`/api/programs/${programId}/deployments`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error?.message||"Deployment action failed");return data;}
function commandsFor(status:DeploymentStatus):DeploymentCommandType[]{const map:Record<DeploymentStatus,DeploymentCommandType[]>={draft:["start","recovery_drill","stop"],queued:["emergency_freeze","stop"],starting:["emergency_freeze","stop"],active:["pause","emergency_freeze","recovery_drill","reconcile","stop"],paused:["resume","emergency_freeze","recovery_drill","reconcile","stop"],frozen:["recovery_drill","reconcile","resume","stop"],failed:["recovery_drill","reconcile","stop"],stopped:["recovery_drill"]};return map[status];}

export function DeploymentCommandCenter({programId,initialDetail,qualifications}:{programId:string;initialDetail:C3ProgramDetail;qualifications:QualificationRecord[]}){
  const [detail,setDetail]=useState(initialDetail),[error,setError]=useState(""),[pending,start]=useTransition();
  const refresh=async()=>{const r=await fetch(`/api/programs/${programId}/deployments`,{cache:"no-store"});const d=await r.json();setDetail(d.detail);};
  const act=(payload:Record<string,unknown>)=>start(async()=>{try{setError("");await post(programId,payload);await refresh();}catch(e){setError(e instanceof Error?e.message:"Action failed");}});
  const healthy=detail.connectors.filter(c=>c.status==="healthy"),qualified=qualifications.filter(q=>q.status==="qualified"&&q.approved_at);
  return <div className="space-y-5">
    {error?<p className="rounded-sm border border-research-red/30 bg-research-red/5 px-3 py-2 text-sm text-research-red">{error}</p>:null}
    <div className="grid gap-4 lg:grid-cols-2">
      <form className="rounded-md border border-border-subtle bg-surface-subtle p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:"create_connector",venue:f.get("venue"),environment:f.get("environment"),product_type:f.get("product_type"),label:f.get("label"),api_key:f.get("api_key"),api_secret:f.get("api_secret"),withdrawals_disabled:f.get("withdrawals_disabled")==="yes"});e.currentTarget.reset();}}>
        <p className="font-medium text-text-institutional">Connect exchange</p><p className="mt-1 text-xs leading-5 text-text-neutral">Trading permission is required. Withdrawal permission must remain disabled. Demo and live credentials are stored separately.</p>
        <div className="mt-3 grid gap-2 sm:grid-cols-3"><select name="venue" className="rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="bybit">Bybit</option><option value="binance">Binance</option></select><select name="product_type" className="rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="spot">Spot</option><option value="perpetual">Perpetual futures</option></select><select name="environment" className="rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="demo">Demo / testnet</option><option value="live">Live canary</option></select></div>
        <input required name="label" placeholder="Connector label" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><input required name="api_key" type="password" autoComplete="new-password" placeholder="API key" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><input required name="api_secret" type="password" autoComplete="new-password" placeholder="API secret" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><label className="mt-3 flex items-start gap-2 text-xs leading-5 text-text-neutral"><input required type="checkbox" name="withdrawals_disabled" value="yes" className="mt-1"/>I confirm withdrawal permission is disabled for this API key.</label><Button className="mt-3" size="sm" disabled={pending}>Validate connector</Button>
      </form>
      <form className="rounded-md border border-border-subtle bg-surface-subtle p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),connector=detail.connectors.find(c=>c.connector_id===f.get("connector_id"));act({action:"create_deployment",connector_id:f.get("connector_id"),qualification_id:f.get("qualification_id"),demo_deployment_id:f.get("demo_deployment_id"),symbols:String(f.get("symbols")||"").split(","),risk_policy:{max_notional_usd:Number(f.get("max_notional_usd")),max_order_notional_usd:Number(f.get("max_order_notional_usd")),max_gross_notional_usd:Number(f.get("max_notional_usd")),max_order_quantity:Number(f.get("max_order_quantity")),max_open_orders:Number(f.get("max_open_orders")),max_open_positions:Number(f.get("max_open_positions")),max_daily_loss_usd:Number(f.get("max_daily_loss_usd")),max_session_loss_usd:Number(f.get("max_session_loss_usd")),close_positions_on_emergency_freeze:f.get("close_positions")==="yes"},confirm_live_canary:connector?.environment==="live"&&f.get("live_confirmation")==="LIVE CANARY"});}}>
        <p className="font-medium text-text-institutional">Create qualified deployment</p><p className="mt-1 text-xs leading-5 text-text-neutral">A deployment is immutably pinned to one approved qualification and its exact strategy, risk, and config hashes.</p>
        <select required name="connector_id" className="mt-3 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="">Healthy connector</option>{healthy.map(c=><option key={c.connector_id} value={c.connector_id}>{c.label} · {c.venue} {c.product_type} {c.environment}</option>)}</select>
        <select required name="qualification_id" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="">Approved qualification</option>{qualified.map(q=><option key={q.qualification_id} value={q.qualification_id}>{q.qualification_id.slice(0,8)} · {q.strategy_spec_hash.slice(0,10)}</option>)}</select>
        <input required name="symbols" defaultValue="BTCUSDT" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><select name="demo_deployment_id" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"><option value="">Demo evidence for live canary</option>{detail.deployments.filter(d=>d.environment==="demo").map(d=><option key={d.deployment_id} value={d.deployment_id}>{d.venue} demo · {d.deployment_id.slice(0,8)}</option>)}</select><div className="mt-2 grid gap-2 sm:grid-cols-2"><input required aria-label="Maximum gross notional" className="rounded-sm border border-border-subtle px-2 py-2" name="max_notional_usd" type="number" min="1" defaultValue="100"/><input required aria-label="Maximum order notional" className="rounded-sm border border-border-subtle px-2 py-2" name="max_order_notional_usd" type="number" min="1" defaultValue="50"/><input required aria-label="Maximum order quantity" className="rounded-sm border border-border-subtle px-2 py-2" name="max_order_quantity" type="number" min="0.00000001" step="any" defaultValue="0.01"/><input required aria-label="Maximum open orders" className="rounded-sm border border-border-subtle px-2 py-2" name="max_open_orders" type="number" min="1" defaultValue="2"/><input required aria-label="Maximum open positions" className="rounded-sm border border-border-subtle px-2 py-2" name="max_open_positions" type="number" min="1" defaultValue="1"/><input required aria-label="Maximum daily loss" className="rounded-sm border border-border-subtle px-2 py-2" name="max_daily_loss_usd" type="number" min="1" defaultValue="25"/><input required aria-label="Maximum session loss" className="rounded-sm border border-border-subtle px-2 py-2" name="max_session_loss_usd" type="number" min="1" defaultValue="40"/></div><label className="mt-2 flex gap-2 text-xs text-text-neutral"><input name="close_positions" value="yes" type="checkbox"/>Close perpetual positions reduce-only during emergency freeze</label><input name="live_confirmation" placeholder="For live, type LIVE CANARY" className="mt-2 w-full rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><Button className="mt-3" size="sm" disabled={pending||!healthy.length||!qualified.length}>Create deployment</Button>
      </form>
    </div>
    <div className="space-y-3">{detail.connectors.map(c=><div key={c.connector_id} className="rounded-md border border-border-subtle p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium text-text-institutional">{c.label}</p><p className="text-xs text-text-neutral">{c.venue} · {c.product_type} · {c.environment} · {c.api_key_hint}</p></div><div className="flex items-center gap-2"><span className="rounded-sm border border-border-subtle px-2 py-1 text-xs uppercase">{c.status}</span><Button size="sm" variant="tertiary" disabled={pending} onClick={()=>act({action:"revoke_connector",connector_id:c.connector_id})}>Revoke</Button></div></div><details className="mt-2"><summary className="cursor-pointer text-xs font-medium text-text-neutral">Replace credentials</summary><form className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act({action:"replace_credentials",connector_id:c.connector_id,api_key:f.get("api_key"),api_secret:f.get("api_secret")});e.currentTarget.reset();}}><input required name="api_key" type="password" autoComplete="new-password" placeholder="New API key" className="rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><input required name="api_secret" type="password" autoComplete="new-password" placeholder="New API secret" className="rounded-sm border border-border-subtle bg-white px-3 py-2 text-sm"/><Button size="sm" variant="secondary" disabled={pending}>Replace</Button></form><p className="mt-1 text-[11px] text-text-neutral">Stored values are never displayed. Enter both values only when rotating this connector.</p></details></div>)}</div>
    <div className="space-y-3">{detail.deployments.length?detail.deployments.map(d=>{const projection=detail.projections.find(p=>p.deployment_id===d.deployment_id);const commands=commandsFor(d.status);return <article key={d.deployment_id} className="rounded-md border border-border-subtle bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-text-institutional">{d.venue.toUpperCase()} {d.product_type} {d.environment} · {d.symbols.join(", ")}</p><p className="mt-1 font-mono text-[11px] text-text-neutral">spec {d.strategy_spec_hash.slice(0,12)} · risk {d.risk_policy_hash.slice(0,12)}</p></div><span className={`rounded-sm border px-2 py-1 text-xs uppercase ${d.status==="frozen"?"border-research-red text-research-red":"border-border-subtle"}`}>{d.status}</span></div><div className="mt-3 grid gap-2 text-xs text-text-neutral sm:grid-cols-3"><span>Balance assets: {Object.keys(projection?.balances||{}).length}</span><span>Open positions: {projection?.positions.length||0}</span><span>Open orders: {projection?.orders.length||0}</span></div>{d.frozen_reason?<p className="mt-2 text-xs text-research-red">Frozen: {d.frozen_reason}</p>:null}<div className="mt-3 flex flex-wrap gap-2">{commands.map(command=><Button key={command} size="sm" variant={command==="emergency_freeze"||command==="stop"?"secondary":"primary"} disabled={pending} onClick={()=>act({action:"command",deployment_id:d.deployment_id,command_type:command})}>{command}</Button>)}</div></article>}):<p className="text-sm text-text-neutral">No deployment has been created. Connect an exchange and qualify an exact strategy first.</p>}</div>
  </div>;
}
