import { randomUUID } from "node:crypto";
import { getDb } from "@/lib/server/persistence/database";
import { getDatabaseProvider } from "@/lib/server/persistence/provider";
import { getPostgresPool } from "@/lib/server/persistence/postgres";
import type { ConnectorCertification, DeploymentIncident, ExecutionSafetyDetail, MemoryPolicyEvaluation, MemoryPolicyRecord, PortfolioSnapshot, PromotionRecord, SafetyPolicyRecord, StreamSession } from "./models";

const iso=(v:unknown)=>v instanceof Date?v.toISOString():String(v),json=<T>(v:unknown,f:T):T=>v==null?f:(typeof v==="string"?JSON.parse(v):v) as T,bool=(v:unknown)=>v===true||v===1||v==="1";
async function rows(pg:string,sq:string,p:unknown[]){return getDatabaseProvider()==="postgres"?(await getPostgresPool().query(pg,p)).rows as Record<string,unknown>[]:getDb().prepare(sq).all(...p) as Record<string,unknown>[];}
async function run(pg:string,sq:string,p:unknown[]){if(getDatabaseProvider()==="postgres")await getPostgresPool().query(pg,p);else getDb().prepare(sq).run(...p);}
const promotion=(r:Record<string,unknown>):PromotionRecord=>({promotion_id:String(r.promotion_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),from_stage:String(r.from_stage),to_stage:String(r.to_stage),status:String(r.status),evidence:json(r.evidence_json,{}),checks:json(r.checks_json,{}),unresolved:json(r.unresolved_json,[]),evidence_hash:String(r.evidence_hash),approved_by_user_id:r.approved_by_user_id?String(r.approved_by_user_id):undefined,approved_at:r.approved_at?iso(r.approved_at):undefined,created_at:iso(r.created_at)});
const safety=(r:Record<string,unknown>):SafetyPolicyRecord=>({deployment_id:String(r.deployment_id),account_id:String(r.account_id),policy:json(r.policy_json,{}) as never,policy_hash:String(r.policy_hash),status:String(r.status),approved_by_user_id:r.approved_by_user_id?String(r.approved_by_user_id):undefined,approved_at:r.approved_at?iso(r.approved_at):undefined,kill_switch_tested_at:r.kill_switch_tested_at?iso(r.kill_switch_tested_at):undefined,recovery_drill_passed_at:r.recovery_drill_passed_at?iso(r.recovery_drill_passed_at):undefined,updated_at:iso(r.updated_at)});
const incident=(r:Record<string,unknown>):DeploymentIncident=>({incident_id:String(r.incident_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),incident_type:String(r.incident_type),severity:r.severity as never,status:r.status as never,summary:String(r.summary),details:json(r.details_json,{}),source_event_id:r.source_event_id?String(r.source_event_id):undefined,created_at:iso(r.created_at),resolved_at:r.resolved_at?iso(r.resolved_at):undefined,resolved_by_user_id:r.resolved_by_user_id?String(r.resolved_by_user_id):undefined});
const portfolio=(r:Record<string,unknown>):PortfolioSnapshot=>({portfolio_snapshot_id:String(r.portfolio_snapshot_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),source_event_id:String(r.source_event_id),equity:r.equity==null?undefined:Number(r.equity),available_balance:r.available_balance==null?undefined:Number(r.available_balance),margin_used:r.margin_used==null?undefined:Number(r.margin_used),realized_pnl:r.realized_pnl==null?undefined:Number(r.realized_pnl),unrealized_pnl:r.unrealized_pnl==null?undefined:Number(r.unrealized_pnl),drawdown_pct:r.drawdown_pct==null?undefined:Number(r.drawdown_pct),exposure:json(r.exposure_json,{}),risk:json(r.risk_json,{}),freshness:json(r.freshness_json,{}),snapshot_hash:String(r.snapshot_hash),observed_at:iso(r.observed_at),ingested_at:iso(r.ingested_at)});
const memoryPolicy=(r:Record<string,unknown>):MemoryPolicyRecord=>({memory_policy_id:String(r.memory_policy_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),mode:r.mode as never,status:r.status as never,thresholds:json(r.thresholds_json,{}) as never,policy_hash:String(r.policy_hash),approved_by_user_id:r.approved_by_user_id?String(r.approved_by_user_id):undefined,approved_at:r.approved_at?iso(r.approved_at):undefined,created_at:iso(r.created_at),updated_at:iso(r.updated_at)});
const evaluation=(r:Record<string,unknown>):MemoryPolicyEvaluation=>({memory_policy_evaluation_id:String(r.memory_policy_evaluation_id),memory_policy_id:String(r.memory_policy_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),assessment_id:r.assessment_id?String(r.assessment_id):undefined,order_intent_id:String(r.order_intent_id),mode:String(r.mode),would_block:bool(r.would_block),applied_block:bool(r.applied_block),reason_codes:json(r.reason_codes_json,[]),requested_quantity:Number(r.requested_quantity),effective_quantity:Number(r.effective_quantity),source_episode_ids:json(r.source_episode_ids_json,[]),outcome:r.outcome?String(r.outcome):undefined,false_block:r.false_block==null?undefined:bool(r.false_block),missed_risk:r.missed_risk==null?undefined:bool(r.missed_risk),evaluated_at:iso(r.evaluated_at),resolved_at:r.resolved_at?iso(r.resolved_at):undefined});
const stream=(r:Record<string,unknown>):StreamSession=>({stream_session_id:String(r.stream_session_id),connector_id:String(r.connector_id),account_id:String(r.account_id),venue:String(r.venue),environment:String(r.environment),product_type:String(r.product_type),status:String(r.status),private_stream_ready:bool(r.private_stream_ready),last_event_at:r.last_event_at?iso(r.last_event_at):undefined,last_reconciled_at:r.last_reconciled_at?iso(r.last_reconciled_at):undefined,reconnect_count:Number(r.reconnect_count),details:json(r.details_json,{}),started_at:iso(r.started_at),stopped_at:r.stopped_at?iso(r.stopped_at):undefined});
const certification=(r:Record<string,unknown>):ConnectorCertification=>({connector_certification_id:String(r.connector_certification_id),venue:String(r.venue),environment:String(r.environment),product_type:String(r.product_type),adapter_version:String(r.adapter_version),status:String(r.status),checks:json(r.checks_json,{}),fault_tests:json(r.fault_tests_json,{}),certification_hash:String(r.certification_hash),certified_at:iso(r.certified_at)});

export const executionSafetyRepository={
 async auditCredentialUse(connectorId:string,accountId:string,workerId:string,purpose:string,outcome:string){await run("INSERT INTO connector_credential_use_audit VALUES ($1,$2,$3,$4,$5,$6,$7)","INSERT INTO connector_credential_use_audit VALUES (?,?,?,?,?,?,?)",[randomUUID(),connectorId,accountId,workerId,purpose,outcome,new Date().toISOString()]);},
 async detail(programId:string,accountId:string):Promise<ExecutionSafetyDetail>{const p=[programId,accountId],[pr,sp,inc,ad,dr,ps,aa,mp,me,ss,cc,ma]=await Promise.all([
  rows("SELECT * FROM deployment_promotions WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC","SELECT * FROM deployment_promotions WHERE program_id=? AND account_id=? ORDER BY created_at DESC",p),
  rows("SELECT s.* FROM deployment_safety_policies s JOIN strategy_deployments d ON d.deployment_id=s.deployment_id WHERE d.program_id=$1 AND s.account_id=$2","SELECT s.* FROM deployment_safety_policies s JOIN strategy_deployments d ON d.deployment_id=s.deployment_id WHERE d.program_id=? AND s.account_id=?",p),
  rows("SELECT * FROM deployment_incidents WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC LIMIT 200","SELECT * FROM deployment_incidents WHERE program_id=? AND account_id=? ORDER BY created_at DESC LIMIT 200",p),
  rows("SELECT a.* FROM external_alert_deliveries a JOIN deployment_incidents i ON i.incident_id=a.incident_id WHERE i.program_id=$1 AND a.account_id=$2 ORDER BY a.created_at DESC LIMIT 200","SELECT a.* FROM external_alert_deliveries a JOIN deployment_incidents i ON i.incident_id=a.incident_id WHERE i.program_id=? AND a.account_id=? ORDER BY a.created_at DESC LIMIT 200",p),
  rows("SELECT r.* FROM deployment_recovery_drills r JOIN strategy_deployments d ON d.deployment_id=r.deployment_id WHERE d.program_id=$1 AND r.account_id=$2 ORDER BY r.created_at DESC","SELECT r.* FROM deployment_recovery_drills r JOIN strategy_deployments d ON d.deployment_id=r.deployment_id WHERE d.program_id=? AND r.account_id=? ORDER BY r.created_at DESC",p),
  rows("SELECT * FROM portfolio_snapshots WHERE program_id=$1 AND account_id=$2 ORDER BY observed_at DESC LIMIT 500","SELECT * FROM portfolio_snapshots WHERE program_id=? AND account_id=? ORDER BY observed_at DESC LIMIT 500",p),
  rows("SELECT * FROM deployment_audit_actions WHERE program_id=$1 AND account_id=$2 ORDER BY occurred_at DESC LIMIT 500","SELECT * FROM deployment_audit_actions WHERE program_id=? AND account_id=? ORDER BY occurred_at DESC LIMIT 500",p),
  rows("SELECT * FROM memory_policy_configs WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC","SELECT * FROM memory_policy_configs WHERE program_id=? AND account_id=? ORDER BY created_at DESC",p),
  rows("SELECT * FROM memory_policy_evaluations WHERE program_id=$1 AND account_id=$2 ORDER BY evaluated_at DESC LIMIT 500","SELECT * FROM memory_policy_evaluations WHERE program_id=? AND account_id=? ORDER BY evaluated_at DESC LIMIT 500",p),
  rows("SELECT s.* FROM connector_stream_sessions s JOIN exchange_connectors c ON c.connector_id=s.connector_id WHERE c.account_id=$2 ORDER BY s.started_at DESC LIMIT 100","SELECT s.* FROM connector_stream_sessions s JOIN exchange_connectors c ON c.connector_id=s.connector_id WHERE c.account_id=? ORDER BY s.started_at DESC LIMIT 100",getDatabaseProvider()==="postgres"?p:[accountId]),
  rows("SELECT * FROM connector_certifications ORDER BY certified_at DESC","SELECT * FROM connector_certifications ORDER BY certified_at DESC",[]),
  rows("SELECT * FROM memory_assessments WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC LIMIT 100","SELECT * FROM memory_assessments WHERE program_id=? AND account_id=? ORDER BY created_at DESC LIMIT 100",p),
 ]);return {promotions:pr.map(promotion),safety_policies:sp.map(safety),incidents:inc.map(incident),alert_deliveries:ad.map(r=>({alert_delivery_id:String(r.alert_delivery_id),incident_id:String(r.incident_id),channel:String(r.channel),destination_hint:String(r.destination_hint),status:String(r.status),attempt_count:Number(r.attempt_count),error_code:r.error_code?String(r.error_code):undefined,created_at:iso(r.created_at),sent_at:r.sent_at?iso(r.sent_at):undefined})),recovery_drills:dr.map(r=>({...r,steps:json(r.steps_json,[]),evidence:json(r.evidence_json,{})})),portfolio_snapshots:ps.map(portfolio),audit_actions:aa.map(r=>({audit_action_id:String(r.audit_action_id),deployment_id:String(r.deployment_id),action_type:String(r.action_type),actor_user_id:String(r.actor_user_id),payload:json(r.payload_json,{}),occurred_at:iso(r.occurred_at)})),memory_policies:mp.map(memoryPolicy),memory_evaluations:me.map(evaluation),stream_sessions:ss.map(stream),certifications:cc.map(certification),latest_assessments:ma.map(r=>({assessment_id:String(r.assessment_id),assessment:String(r.assessment),support_count:Number(r.support_count),drift_ratio:r.drift_ratio==null?undefined:Number(r.drift_ratio),source_episode_ids:json(r.source_episode_ids_json,[]),empirical_positive_rate:r.empirical_positive_rate==null?undefined:Number(r.empirical_positive_rate),created_at:iso(r.created_at)})) as never};},
 async saveSafety(v:SafetyPolicyRecord){const p=[v.deployment_id,v.account_id,JSON.stringify(v.policy),v.policy_hash,v.status,v.approved_by_user_id??null,v.approved_at??null,v.kill_switch_tested_at??null,v.recovery_drill_passed_at??null,v.updated_at];await run("INSERT INTO deployment_safety_policies VALUES ($1,$2,$3::jsonb,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(deployment_id) DO UPDATE SET policy_json=EXCLUDED.policy_json,policy_hash=EXCLUDED.policy_hash,status=EXCLUDED.status,approved_by_user_id=EXCLUDED.approved_by_user_id,approved_at=EXCLUDED.approved_at,kill_switch_tested_at=COALESCE(EXCLUDED.kill_switch_tested_at,deployment_safety_policies.kill_switch_tested_at),recovery_drill_passed_at=COALESCE(EXCLUDED.recovery_drill_passed_at,deployment_safety_policies.recovery_drill_passed_at),updated_at=EXCLUDED.updated_at","INSERT INTO deployment_safety_policies VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(deployment_id) DO UPDATE SET policy_json=excluded.policy_json,policy_hash=excluded.policy_hash,status=excluded.status,approved_by_user_id=excluded.approved_by_user_id,approved_at=excluded.approved_at,kill_switch_tested_at=COALESCE(excluded.kill_switch_tested_at,deployment_safety_policies.kill_switch_tested_at),recovery_drill_passed_at=COALESCE(excluded.recovery_drill_passed_at,deployment_safety_policies.recovery_drill_passed_at),updated_at=excluded.updated_at",p);return v;},
 async findSafety(deploymentId:string,accountId:string){const r=await rows("SELECT * FROM deployment_safety_policies WHERE deployment_id=$1 AND account_id=$2","SELECT * FROM deployment_safety_policies WHERE deployment_id=? AND account_id=?",[deploymentId,accountId]);return r[0]?safety(r[0]):undefined;},
 async savePromotion(v:PromotionRecord){await run("INSERT INTO deployment_promotions VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10::jsonb,$11,$12,$13,$14)","INSERT INTO deployment_promotions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.promotion_id,v.deployment_id,v.program_id,v.account_id,v.from_stage,v.to_stage,v.status,JSON.stringify(v.evidence),JSON.stringify(v.checks),JSON.stringify(v.unresolved),v.evidence_hash,v.approved_by_user_id??null,v.approved_at??null,v.created_at]);return v;},
 async saveIncident(v:DeploymentIncident){await run("INSERT INTO deployment_incidents VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13)","INSERT INTO deployment_incidents VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.incident_id,v.deployment_id,v.program_id,v.account_id,v.incident_type,v.severity,v.status,v.summary,JSON.stringify(v.details),v.source_event_id??null,v.created_at,v.resolved_at??null,v.resolved_by_user_id??null]);return v;},
 async resolveIncident(id:string,accountId:string,userId:string){const now=new Date().toISOString();await run("UPDATE deployment_incidents SET status='resolved',resolved_at=$3,resolved_by_user_id=$4 WHERE incident_id=$1 AND account_id=$2","UPDATE deployment_incidents SET status='resolved',resolved_at=?,resolved_by_user_id=? WHERE incident_id=? AND account_id=?",getDatabaseProvider()==="postgres"?[id,accountId,now,userId]:[now,userId,id,accountId]);},
 async saveAlert(id:string,incidentId:string,accountId:string,channel:string,hint:string){const now=new Date().toISOString();await run("INSERT INTO external_alert_deliveries VALUES ($1,$2,$3,$4,$5,'queued',0,NULL,$6,NULL)","INSERT INTO external_alert_deliveries VALUES (?,?,?,?,?,'queued',0,NULL,?,NULL)",[id,incidentId,accountId,channel,hint,now]);},
 async savePortfolio(v:PortfolioSnapshot){await run("INSERT INTO portfolio_snapshots VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,$15,$16,$17) ON CONFLICT(snapshot_hash) DO NOTHING","INSERT OR IGNORE INTO portfolio_snapshots VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.portfolio_snapshot_id,v.deployment_id,v.program_id,v.account_id,v.source_event_id,v.equity??null,v.available_balance??null,v.margin_used??null,v.realized_pnl??null,v.unrealized_pnl??null,v.drawdown_pct??null,JSON.stringify(v.exposure),JSON.stringify(v.risk),JSON.stringify(v.freshness),v.snapshot_hash,v.observed_at,v.ingested_at]);return v;},
 async saveMemoryPolicy(v:MemoryPolicyRecord){await run("INSERT INTO memory_policy_configs VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12) ON CONFLICT(deployment_id) DO UPDATE SET mode=EXCLUDED.mode,status=EXCLUDED.status,thresholds_json=EXCLUDED.thresholds_json,policy_hash=EXCLUDED.policy_hash,approved_by_user_id=EXCLUDED.approved_by_user_id,approved_at=EXCLUDED.approved_at,updated_at=EXCLUDED.updated_at","INSERT INTO memory_policy_configs VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(deployment_id) DO UPDATE SET mode=excluded.mode,status=excluded.status,thresholds_json=excluded.thresholds_json,policy_hash=excluded.policy_hash,approved_by_user_id=excluded.approved_by_user_id,approved_at=excluded.approved_at,updated_at=excluded.updated_at",[v.memory_policy_id,v.deployment_id,v.program_id,v.account_id,v.mode,v.status,JSON.stringify(v.thresholds),v.policy_hash,v.approved_by_user_id??null,v.approved_at??null,v.created_at,v.updated_at]);return v;},
 async findMemoryPolicy(deploymentId:string,accountId:string){const r=await rows("SELECT * FROM memory_policy_configs WHERE deployment_id=$1 AND account_id=$2","SELECT * FROM memory_policy_configs WHERE deployment_id=? AND account_id=?",[deploymentId,accountId]);return r[0]?memoryPolicy(r[0]):undefined;},
 async saveEvaluation(v:MemoryPolicyEvaluation){const pg=getDatabaseProvider()==="postgres";await run("INSERT INTO memory_policy_evaluations VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14::jsonb,$15,$16,$17,$18,$19)","INSERT INTO memory_policy_evaluations VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.memory_policy_evaluation_id,v.memory_policy_id,v.deployment_id,v.program_id,v.account_id,v.assessment_id??null,v.order_intent_id,v.mode,pg?v.would_block:(v.would_block?1:0),pg?v.applied_block:(v.applied_block?1:0),JSON.stringify(v.reason_codes),v.requested_quantity,v.effective_quantity,JSON.stringify(v.source_episode_ids),v.outcome??null,v.false_block===undefined?null:pg?v.false_block:(v.false_block?1:0),v.missed_risk===undefined?null:pg?v.missed_risk:(v.missed_risk?1:0),v.evaluated_at,v.resolved_at??null]);return v;},
 async saveDrill(v:{id:string;deploymentId:string;accountId:string;status:string;steps:unknown[];evidence:Record<string,unknown>;userId:string;createdAt:string;completedAt?:string}){await run("INSERT INTO deployment_recovery_drills VALUES ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,$8,$9)","INSERT INTO deployment_recovery_drills VALUES (?,?,?,?,?,?,?,?,?)",[v.id,v.deploymentId,v.accountId,v.status,JSON.stringify(v.steps),JSON.stringify(v.evidence),v.userId,v.createdAt,v.completedAt??null]);},
 async saveStream(v:StreamSession){const pg=getDatabaseProvider()==="postgres";await run("INSERT INTO connector_stream_sessions VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14)","INSERT INTO connector_stream_sessions VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.stream_session_id,v.connector_id,v.account_id,v.venue,v.environment,v.product_type,v.status,pg?v.private_stream_ready:(v.private_stream_ready?1:0),v.last_event_at??null,v.last_reconciled_at??null,v.reconnect_count,JSON.stringify(v.details),v.started_at,v.stopped_at??null]);return v;},
 async saveCertification(v:ConnectorCertification){await run("INSERT INTO connector_certifications VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10) ON CONFLICT(certification_hash) DO NOTHING","INSERT OR IGNORE INTO connector_certifications VALUES (?,?,?,?,?,?,?,?,?,?)",[v.connector_certification_id,v.venue,v.environment,v.product_type,v.adapter_version,v.status,JSON.stringify(v.checks),JSON.stringify(v.fault_tests),v.certification_hash,v.certified_at]);return v;},
 async latestStream(connectorId:string,accountId:string){const r=await rows("SELECT * FROM connector_stream_sessions WHERE connector_id=$1 AND account_id=$2 ORDER BY started_at DESC LIMIT 1","SELECT * FROM connector_stream_sessions WHERE connector_id=? AND account_id=? ORDER BY started_at DESC LIMIT 1",[connectorId,accountId]);return r[0]?stream(r[0]):undefined;},
 async latestCertification(venue:string,environment:string,productType:string){const r=await rows("SELECT * FROM connector_certifications WHERE venue=$1 AND environment=$2 AND product_type=$3 ORDER BY certified_at DESC LIMIT 1","SELECT * FROM connector_certifications WHERE venue=? AND environment=? AND product_type=? ORDER BY certified_at DESC LIMIT 1",[venue,environment,productType]);return r[0]?certification(r[0]):undefined;},
 async saveAudit(input:{deploymentId:string;programId:string;accountId:string;actionType:string;actorUserId:string;payload:Record<string,unknown>}){const now=new Date().toISOString(),id=randomUUID();await run("INSERT INTO deployment_audit_actions VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8)","INSERT INTO deployment_audit_actions VALUES (?,?,?,?,?,?,?,?)",[id,input.deploymentId,input.programId,input.accountId,input.actionType,input.actorUserId,JSON.stringify(input.payload),now]);return {audit_action_id:id,occurred_at:now};},
 async resolveEvaluation(id:string,accountId:string,outcome:string,falseBlock:boolean,missedRisk:boolean){const now=new Date().toISOString();await run("UPDATE memory_policy_evaluations SET outcome=$3,false_block=$4,missed_risk=$5,resolved_at=$6 WHERE memory_policy_evaluation_id=$1 AND account_id=$2","UPDATE memory_policy_evaluations SET outcome=?,false_block=?,missed_risk=?,resolved_at=? WHERE memory_policy_evaluation_id=? AND account_id=?",getDatabaseProvider()==="postgres"?[id,accountId,outcome,falseBlock,missedRisk,now]:[outcome,falseBlock?1:0,missedRisk?1:0,now,id,accountId]);return {memory_policy_evaluation_id:id,outcome,false_block:falseBlock,missed_risk:missedRisk,resolved_at:now};},
 async findEvaluation(id:string,accountId:string){const r=await rows("SELECT * FROM memory_policy_evaluations WHERE memory_policy_evaluation_id=$1 AND account_id=$2","SELECT * FROM memory_policy_evaluations WHERE memory_policy_evaluation_id=? AND account_id=?",[id,accountId]);return r[0]?evaluation(r[0]):undefined;},
 async claimAlert():Promise<(Record<string,unknown>&{details:Record<string,unknown>})|undefined>{const found=await rows("SELECT a.*,i.deployment_id,i.program_id,i.severity,i.summary,i.details_json FROM external_alert_deliveries a JOIN deployment_incidents i ON i.incident_id=a.incident_id WHERE a.status='queued' ORDER BY a.created_at LIMIT 1","SELECT a.*,i.deployment_id,i.program_id,i.severity,i.summary,i.details_json FROM external_alert_deliveries a JOIN deployment_incidents i ON i.incident_id=a.incident_id WHERE a.status='queued' ORDER BY a.created_at LIMIT 1",[]);const value=found[0];if(!value)return undefined;await run("UPDATE external_alert_deliveries SET status='processing',attempt_count=attempt_count+1 WHERE alert_delivery_id=$1 AND status='queued'","UPDATE external_alert_deliveries SET status='processing',attempt_count=attempt_count+1 WHERE alert_delivery_id=? AND status='queued'",[value.alert_delivery_id]);return {...value,details:json(value.details_json,{})};},
 async completeAlert(id:string,status:"queued"|"sent"|"failed"|"ops_visible",errorCode?:string){const now=new Date().toISOString();await run("UPDATE external_alert_deliveries SET status=$2,error_code=$3,sent_at=$4 WHERE alert_delivery_id=$1","UPDATE external_alert_deliveries SET status=?,error_code=?,sent_at=? WHERE alert_delivery_id=?",getDatabaseProvider()==="postgres"?[id,status,errorCode??null,status==="sent"||status==="ops_visible"?now:null]:[status,errorCode??null,status==="sent"||status==="ops_visible"?now:null,id]);},
 async eventsAfter(programId:string,accountId:string,after:string|undefined,limit=100){const [occurredAt,eventId=""]=after?.split("|")??[],pg=after?[programId,accountId,occurredAt,eventId,limit]:[programId,accountId,limit],sq=after?[programId,accountId,occurredAt,occurredAt,eventId,limit]:[programId,accountId,limit];return rows(after?"SELECT * FROM deployment_events WHERE program_id=$1 AND account_id=$2 AND (occurred_at,deployment_event_id)>($3::timestamptz,$4) ORDER BY occurred_at,deployment_event_id LIMIT $5":"SELECT * FROM deployment_events WHERE program_id=$1 AND account_id=$2 ORDER BY occurred_at DESC LIMIT $3",after?"SELECT * FROM deployment_events WHERE program_id=? AND account_id=? AND (occurred_at>? OR (occurred_at=? AND deployment_event_id>?)) ORDER BY occurred_at,deployment_event_id LIMIT ?":"SELECT * FROM deployment_events WHERE program_id=? AND account_id=? ORDER BY occurred_at DESC LIMIT ?",getDatabaseProvider()==="postgres"?pg:sq);},
};
