import { createHash, randomUUID } from "node:crypto";
import { getResearchProgramDetail } from "@/lib/server/research-programs/service";
import { c3Repository } from "@/lib/server/research-c3/repository";
import { c4Repository } from "@/lib/server/research-c4/repository";
import type { StrategyDeployment } from "@/lib/server/research-c3/models";
import { executionSafetyRepository } from "./repository";
import type { DeploymentIncident, LiveSafetyPolicy, MemoryPolicyEvaluation, MemoryPolicyRecord, PortfolioSnapshot, PromotionRecord, SafetyPolicyRecord } from "./models";

const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item)).digest("hex");
const finite=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined;};
async function program(programId:string,accountId:string){const value=await getResearchProgramDetail(programId,accountId);if(!value)throw new Error("program_not_found");return value;}
async function deployment(id:string,accountId:string){const value=await c3Repository.findDeployment(id,accountId);if(!value)throw new Error("deployment_not_found");return value;}

export async function getExecutionSafetyDetail(programId:string,accountId:string){await program(programId,accountId);return executionSafetyRepository.detail(programId,accountId);}

export function normalizeSafetyPolicy(value:Record<string,unknown>,symbols:string[]):LiveSafetyPolicy{
  const policy:LiveSafetyPolicy={allowed_symbols:[...new Set((Array.isArray(value.allowed_symbols)?value.allowed_symbols:symbols).map(String).map(s=>s.trim().toUpperCase()).filter(Boolean))],max_order_quantity:Number(value.max_order_quantity),max_order_notional_usd:Number(value.max_order_notional_usd),max_gross_notional_usd:Number(value.max_gross_notional_usd),max_open_orders:Number(value.max_open_orders),max_open_positions:Number(value.max_open_positions),max_daily_loss_usd:Number(value.max_daily_loss_usd),max_session_loss_usd:Number(value.max_session_loss_usd),close_positions_on_emergency_freeze:value.close_positions_on_emergency_freeze===true,allow_reduce_only_when_frozen:true};
  if(!policy.allowed_symbols.length||policy.allowed_symbols.some(s=>!symbols.includes(s)))throw new Error("safety_symbol_allowlist_invalid");
  for(const key of ["max_order_quantity","max_order_notional_usd","max_gross_notional_usd","max_open_orders","max_open_positions","max_daily_loss_usd","max_session_loss_usd"] as const)if(!Number.isFinite(policy[key])||policy[key]<=0)throw new Error(`safety_policy_invalid:${key}`);
  if(!Number.isInteger(policy.max_open_orders)||!Number.isInteger(policy.max_open_positions))throw new Error("safety_policy_count_invalid");
  if(policy.max_order_notional_usd>policy.max_gross_notional_usd)throw new Error("order_notional_exceeds_gross_cap");
  return policy;
}

export async function configureSafetyPolicy(input:{deploymentId:string;accountId:string;userId:string;policy:Record<string,unknown>;approve:boolean}){
  const d=await deployment(input.deploymentId,input.accountId),policy=normalizeSafetyPolicy(input.policy,d.symbols),now=new Date().toISOString(),record:SafetyPolicyRecord={deployment_id:d.deployment_id,account_id:d.account_id,policy,policy_hash:hash(policy),status:input.approve?"approved":"draft",approved_by_user_id:input.approve?input.userId:undefined,approved_at:input.approve?now:undefined,updated_at:now};await executionSafetyRepository.saveSafety(record);return record;
}

export async function evaluateDemoToLive(input:{demoDeploymentId:string;accountId:string;userId:string;approve:boolean;minimumClosedTrades?:number;minimumDemoDays?:number}){
  const d=await deployment(input.demoDeploymentId,input.accountId);if(d.environment!=="demo")throw new Error("demo_deployment_required");
  const [memory,detail,safety]=await Promise.all([c4Repository.detail(d.program_id,d.account_id),executionSafetyRepository.detail(d.program_id,d.account_id),executionSafetyRepository.findSafety(d.deployment_id,d.account_id)]),closed=memory.episodes.filter(e=>e.deployment_id===d.deployment_id&&e.status==="closed"),start=Date.parse(d.started_at??d.created_at),end=Date.parse(d.stopped_at??new Date().toISOString()),days=Math.max(0,(end-start)/86_400_000),minimumTrades=input.minimumClosedTrades??20,minimumDays=input.minimumDemoDays??7,critical=detail.incidents.filter(i=>i.deployment_id===d.deployment_id&&i.status==="open"&&i.severity==="critical");
  const checks={minimum_demo_duration:{required:minimumDays,observed:days,pass:days>=minimumDays},minimum_closed_trades:{required:minimumTrades,observed:closed.length,pass:closed.length>=minimumTrades},reconciliation_healthy:{pass:Boolean(d.last_reconciled_at)},critical_incidents:{observed:critical.length,pass:critical.length===0},safety_policy_approved:{pass:safety?.status==="approved"},kill_switch_tested:{pass:Boolean(safety?.kill_switch_tested_at)},recovery_drill_passed:{pass:Boolean(safety?.recovery_drill_passed_at)}};const unresolved=Object.entries(checks).filter(([,v])=>v.pass!==true).map(([key])=>key),now=new Date().toISOString(),evidence={demo_deployment_id:d.deployment_id,strategy_spec_hash:d.strategy_spec_hash,risk_policy_hash:d.risk_policy_hash,config_hash:d.config_hash,closed_trade_ids:closed.map(e=>e.episode_id),last_reconciled_at:d.last_reconciled_at,period:{started_at:d.started_at??d.created_at,ended_at:d.stopped_at??now,days}},status=unresolved.length?"blocked":input.approve?"approved":"ready";
  const record:PromotionRecord={promotion_id:randomUUID(),deployment_id:d.deployment_id,program_id:d.program_id,account_id:d.account_id,from_stage:"demo",to_stage:"live_canary",status,evidence,checks,unresolved,evidence_hash:hash({evidence,checks}),approved_by_user_id:status==="approved"?input.userId:undefined,approved_at:status==="approved"?now:undefined,created_at:now};await executionSafetyRepository.savePromotion(record);return record;
}

export async function runRecoveryDrill(input:{deploymentId:string;accountId:string;userId:string}){const d=await deployment(input.deploymentId,input.accountId),policy=await executionSafetyRepository.findSafety(d.deployment_id,d.account_id);if(!policy||policy.status!=="approved")throw new Error("approved_safety_policy_required");const detail=await c3Repository.detail(d.program_id,d.account_id),projection=detail.projections.find(p=>p.deployment_id===d.deployment_id),steps=["freeze_new_orders","cancel_open_orders","optional_reduce_only_close","reconcile_exchange_state","verify_read_only"],now=new Date().toISOString(),checks={projection_available:Boolean(projection),connector_healthy:projection?.health.status==="healthy",reconciliation_recorded:Boolean(d.last_reconciled_at),no_open_orders_after_freeze:(projection?.orders.length??0)===0},pass=Object.values(checks).every(Boolean),id=randomUUID();await executionSafetyRepository.saveDrill({id,deploymentId:d.deployment_id,accountId:d.account_id,status:pass?"passed":"failed",steps,evidence:{checks,snapshot_hash:projection?.snapshot_hash},userId:input.userId,createdAt:now,completedAt:now});if(pass)await executionSafetyRepository.saveSafety({...policy,kill_switch_tested_at:now,recovery_drill_passed_at:now,updated_at:now});return {recovery_drill_id:id,status:pass?"passed":"failed",checks};}

export async function createDeploymentIncident(input:{deployment:StrategyDeployment;type:string;severity:"info"|"warning"|"critical";summary:string;details?:Record<string,unknown>;sourceEventId?:string}){const now=new Date().toISOString(),record:DeploymentIncident={incident_id:randomUUID(),deployment_id:input.deployment.deployment_id,program_id:input.deployment.program_id,account_id:input.deployment.account_id,incident_type:input.type,severity:input.severity,status:"open",summary:input.summary.slice(0,240),details:input.details??{},source_event_id:input.sourceEventId,created_at:now};await executionSafetyRepository.saveIncident(record);if(input.severity==="critical"){const endpoint=process.env.EXECUTION_INCIDENT_WEBHOOK_URL;await executionSafetyRepository.saveAlert(randomUUID(),record.incident_id,record.account_id,endpoint?"webhook":"ops_queue",endpoint?"configured webhook":"admin operations");}return record;}
export async function resolveDeploymentIncident(input:{incidentId:string;accountId:string;userId:string}){await executionSafetyRepository.resolveIncident(input.incidentId,input.accountId,input.userId);return {incident_id:input.incidentId,status:"resolved"};}

const USD_BALANCE_ASSETS=new Set(["USD","USDT","USDC","BUSD","FDUSD"]);
function stablecoinValue(value:Record<string,number>){const entries=Object.entries(value).filter(([asset])=>USD_BALANCE_ASSETS.has(asset.toUpperCase()));return entries.length?entries.reduce((sum,[,amount])=>sum+(Number.isFinite(amount)?amount:0),0):undefined;}
export async function recordPortfolioSnapshot(input:{deployment:StrategyDeployment;sourceEventId:string;balances:Record<string,number>;positions:Array<Record<string,unknown>>;health:Record<string,unknown>;observedAt:string}){const equity=stablecoinValue(input.balances),unrealized=input.positions.reduce((sum,p)=>sum+(finite(p.unrealized_pnl)??0),0),realized=input.positions.reduce((sum,p)=>sum+(finite(p.realized_pnl)??0),0),gross=input.positions.reduce((sum,p)=>sum+Math.abs((finite(p.qty)??0)*(finite(p.avg_entry_price)??0)),0),policy=await executionSafetyRepository.findSafety(input.deployment.deployment_id,input.deployment.account_id),risk={gross_notional_usd:gross,risk_budget_consumed_pct:policy?gross/policy.policy.max_gross_notional_usd:undefined,open_positions:input.positions.filter(p=>(finite(p.qty)??0)!==0).length},body={deployment_id:input.deployment.deployment_id,equity,unrealized,realized,gross,observed_at:input.observedAt},record:PortfolioSnapshot={portfolio_snapshot_id:randomUUID(),deployment_id:input.deployment.deployment_id,program_id:input.deployment.program_id,account_id:input.deployment.account_id,source_event_id:input.sourceEventId,equity,available_balance:equity,margin_used:undefined,realized_pnl:realized,unrealized_pnl:unrealized,drawdown_pct:undefined,exposure:{gross_notional_usd:gross,positions:input.positions,balances:input.balances},risk,freshness:{health_status:input.health.status,observed_at:input.observedAt,source:"exchange_rest",valuation_scope:equity===undefined?"unavailable":"usd_stablecoin_balances_only",non_usd_assets_unvalued:Object.keys(input.balances).filter(asset=>!USD_BALANCE_ASSETS.has(asset.toUpperCase()))},snapshot_hash:hash(body),observed_at:input.observedAt,ingested_at:new Date().toISOString()};await executionSafetyRepository.savePortfolio(record);return record;}

export async function configureMemoryPolicy(input:{deploymentId:string;accountId:string;userId:string;mode:"shadow"|"enforced";approve:boolean;thresholds:Record<string,unknown>}){const d=await deployment(input.deploymentId,input.accountId),minimum=Math.max(8,Number(input.thresholds.minimum_support??20)),drift=Number(input.thresholds.maximum_drift_ratio??1.5);if(!Number.isFinite(minimum)||!Number.isFinite(drift)||drift<=0)throw new Error("memory_policy_threshold_invalid");if(input.mode==="enforced"&&!input.approve)throw new Error("memory_policy_explicit_approval_required");const now=new Date().toISOString(),thresholds={minimum_support:minimum,maximum_drift_ratio:drift,block_assessments:["block"],block_on_insufficient_evidence:input.thresholds.block_on_insufficient_evidence===true},existing=await executionSafetyRepository.findMemoryPolicy(d.deployment_id,d.account_id),record:MemoryPolicyRecord={memory_policy_id:existing?.memory_policy_id??randomUUID(),deployment_id:d.deployment_id,program_id:d.program_id,account_id:d.account_id,mode:input.mode,status:input.approve?"approved":"draft",thresholds,policy_hash:hash({mode:input.mode,thresholds}),approved_by_user_id:input.approve?input.userId:undefined,approved_at:input.approve?now:undefined,created_at:existing?.created_at??now,updated_at:now};await executionSafetyRepository.saveMemoryPolicy(record);return record;}

export async function evaluateMemoryPolicyForOrder(input:{deploymentId:string;accountId:string;orderIntentId:string;requestedQuantity:number;assessmentId?:string}){const d=await deployment(input.deploymentId,input.accountId),[policy,memory]=await Promise.all([executionSafetyRepository.findMemoryPolicy(d.deployment_id,d.account_id),c4Repository.detail(d.program_id,d.account_id)]);if(!policy)return {would_block:false,applied_block:false,effective_quantity:input.requestedQuantity,reason_codes:["memory_policy_not_configured"]};const assessment=input.assessmentId?memory.assessments.find(a=>a.assessment_id===input.assessmentId):memory.assessments[0],reasons:string[]=[];if(!assessment)reasons.push("memory_assessment_missing");else{if(memory.calibration.status==="not_available")reasons.push("memory_calibration_unavailable");if(assessment.support_count<policy.thresholds.minimum_support)reasons.push("support_below_policy_minimum");if(assessment.drift_ratio!==undefined&&assessment.drift_ratio>policy.thresholds.maximum_drift_ratio)reasons.push("state_drift_above_policy_maximum");if(policy.thresholds.block_assessments.includes(assessment.assessment))reasons.push("assessment_blocked");if(assessment.assessment==="insufficient_evidence"&&policy.thresholds.block_on_insufficient_evidence)reasons.push("insufficient_evidence_blocked");}const wouldBlock=Boolean(reasons.length),applied=wouldBlock&&policy.mode==="enforced"&&policy.status==="approved",now=new Date().toISOString(),record:MemoryPolicyEvaluation={memory_policy_evaluation_id:randomUUID(),memory_policy_id:policy.memory_policy_id,deployment_id:d.deployment_id,program_id:d.program_id,account_id:d.account_id,assessment_id:assessment?.assessment_id,order_intent_id:input.orderIntentId,mode:policy.mode,would_block:wouldBlock,applied_block:applied,reason_codes:reasons,requested_quantity:input.requestedQuantity,effective_quantity:applied?0:input.requestedQuantity,source_episode_ids:assessment?.source_episode_ids??[],evaluated_at:now};await executionSafetyRepository.saveEvaluation(record);return record;}

export async function authorizeOrderIntent(input:{deploymentId:string;accountId:string;orderIntentId:string;symbol:string;quantity:number;price:number;reduceOnly:boolean;assessmentId?:string}){
  const d=await deployment(input.deploymentId,input.accountId),[policy,c3,execution,connector]=await Promise.all([executionSafetyRepository.findSafety(d.deployment_id,d.account_id),c3Repository.detail(d.program_id,d.account_id),executionSafetyRepository.detail(d.program_id,d.account_id),c3Repository.findConnector(d.connector_id,d.account_id)]);
  const reasons:string[]=[],projection=c3.projections.find(item=>item.deployment_id===d.deployment_id),latest=execution.portfolio_snapshots.find(item=>item.deployment_id===d.deployment_id),openCritical=execution.incidents.filter(item=>item.deployment_id===d.deployment_id&&item.status==="open"&&item.severity==="critical"),promotion=execution.promotions.find(item=>item.status==="approved"&&item.to_stage==="live_canary"&&item.evidence.strategy_spec_hash===d.strategy_spec_hash),stream=execution.stream_sessions.find(item=>item.connector_id===d.connector_id),certification=execution.certifications.find(item=>item.venue===d.venue&&item.environment===d.environment&&item.product_type===d.product_type);
  const symbol=input.symbol.trim().toUpperCase(),quantity=finite(input.quantity)??0,price=finite(input.price)??0,notional=Math.abs(quantity*price),gross=finite(latest?.exposure.gross_notional_usd)??0,dailyPnl=latest?.realized_pnl??0,sessionPnl=(latest?.realized_pnl??0)+(latest?.unrealized_pnl??0),projectionAge=projection?Math.max(0,(Date.now()-Date.parse(projection.updated_at))/1000):Infinity;
  if(!policy||policy.status!=="approved")reasons.push("approved_safety_policy_required");
  else{
    if(!policy.policy.allowed_symbols.includes(symbol))reasons.push("symbol_not_allowed");
    if(quantity<=0||quantity>policy.policy.max_order_quantity)reasons.push("order_quantity_limit");
    if(price<=0||notional>policy.policy.max_order_notional_usd)reasons.push("order_notional_limit");
    if(gross+(input.reduceOnly?0:notional)>policy.policy.max_gross_notional_usd)reasons.push("gross_notional_limit");
    if((projection?.orders.length??0)>=policy.policy.max_open_orders&&!input.reduceOnly)reasons.push("open_order_limit");
    if((projection?.positions.filter(item=>(finite(item.qty)??0)!==0).length??0)>=policy.policy.max_open_positions&&!input.reduceOnly)reasons.push("open_position_limit");
    if(dailyPnl<=-Math.abs(policy.policy.max_daily_loss_usd))reasons.push("daily_loss_limit");
    if(sessionPnl<=-Math.abs(policy.policy.max_session_loss_usd))reasons.push("session_loss_limit");
  }
  if(d.status!=="active"&&!input.reduceOnly)reasons.push("deployment_not_active");
  if(!connector||connector.status!=="healthy"||projectionAge>60||projection?.health.status!=="healthy")reasons.push("connector_unhealthy_or_stale");
  if(!d.last_reconciled_at)reasons.push("reconciliation_required");
  if(openCritical.length)reasons.push("critical_incident_unresolved");
  if(d.environment==="live"){
    if(!promotion)reasons.push("demo_qualification_required");
    if(!policy?.kill_switch_tested_at||!policy.recovery_drill_passed_at)reasons.push("kill_switch_test_required");
    if(!stream?.private_stream_ready||stream.status!=="healthy")reasons.push("private_stream_not_ready");
    if(certification?.status!=="certified")reasons.push("connector_not_certified");
  }
  const memory=await evaluateMemoryPolicyForOrder({deploymentId:d.deployment_id,accountId:d.account_id,orderIntentId:input.orderIntentId,requestedQuantity:quantity,assessmentId:input.assessmentId});
  if(memory.applied_block)reasons.push(...memory.reason_codes.map(code=>`memory:${code}`));
  const onlyFrozenReduce=input.reduceOnly&&d.status==="frozen"&&reasons.every(code=>code==="deployment_not_active");
  return {allowed:reasons.length===0||onlyFrozenReduce,reason_codes:reasons,effective_quantity:reasons.length===0||onlyFrozenReduce?Math.min(quantity,memory.effective_quantity):0,memory_evaluation:memory,policy_hash:policy?.policy_hash,projection_hash:projection?.snapshot_hash};
}

export async function resolveMemoryPolicyEvaluation(input:{evaluationId:string;accountId:string;outcome:"positive"|"negative"|"neutral"}){const value=await executionSafetyRepository.findEvaluation(input.evaluationId,input.accountId);if(!value)throw new Error("memory_policy_evaluation_not_found");const positive=input.outcome==="positive",negative=input.outcome==="negative";return executionSafetyRepository.resolveEvaluation(value.memory_policy_evaluation_id,input.accountId,input.outcome,value.applied_block&&positive,!value.applied_block&&negative);}
