import type { EntitlementSnapshot } from "@/lib/contracts/entitlements";
import type { PlanId } from "@/lib/contracts/account";

type EntitlementTemplate = Omit<EntitlementSnapshot, "account_id" | "effective_at" | "source_of_truth">;

export const PLAN_MATRIX: Record<PlanId, EntitlementTemplate> = {
  explorer: {
    plan_id: "explorer",
    analyses_per_month: 3,
    can_upload_trade_csv: true,
    can_upload_bundle: false,
    can_upload_research_bundle: false,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_execution: true,
    can_view_regimes: false,
    can_view_stability: false,
    can_view_full_report: false,
    can_export_report: false,
    history_retention_days: 30,
    processing_priority: "standard",
    consulting_cta_variant: "soft",
  },
  professional: {
    plan_id: "professional",
    analyses_per_month: 25,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: false,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_execution: true,
    can_view_regimes: false,
    can_view_stability: false,
    can_view_full_report: true,
    can_export_report: true,
    history_retention_days: 365,
    processing_priority: "priority",
    consulting_cta_variant: "serious",
  },
  research_lab: {
    plan_id: "research_lab",
    analyses_per_month: 100,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: true,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_execution: true,
    can_view_regimes: true,
    can_view_stability: true,
    can_view_full_report: true,
    can_export_report: true,
    history_retention_days: 730,
    processing_priority: "premium",
    consulting_cta_variant: "institutional",
  },
  advisory: {
    plan_id: "advisory",
    analyses_per_month: 250,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: true,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_execution: true,
    can_view_regimes: true,
    can_view_stability: true,
    can_view_full_report: true,
    can_export_report: true,
    history_retention_days: 1095,
    processing_priority: "premium",
    consulting_cta_variant: "institutional",
  },
};
