import type { LaunchPlanId, LegacyPlanId, PlanId } from "@/lib/contracts/account";
import type { EntitlementSnapshot } from "@/lib/contracts/entitlements";

type EntitlementTemplate = Omit<EntitlementSnapshot, "account_id" | "effective_at" | "source_of_truth">;

export const LAUNCH_PLAN_IDS = ["free", "explorer", "pro", "team", "research_desk"] as const satisfies readonly LaunchPlanId[];

export const LEGACY_PLAN_ALIASES: Record<LegacyPlanId, LaunchPlanId> = {
  individual: "explorer",
  professional: "explorer",
  research_lab: "pro",
  advisory: "research_desk",
};

export const PLAN_LABELS: Record<LaunchPlanId, string> = {
  free: "Free",
  explorer: "Explorer",
  pro: "Pro",
  team: "Team",
  research_desk: "Research Desk",
};

export const PLAN_PRICE_COPY: Record<LaunchPlanId, string> = {
  free: "$0",
  explorer: "$39/mo",
  pro: "$99/mo",
  team: "$399/mo",
  research_desk: "From $1,000",
};

export function canonicalPlanId(planId: PlanId | string | undefined): LaunchPlanId {
  if (planId === "free" || planId === "explorer" || planId === "pro" || planId === "team" || planId === "research_desk") return planId;
  if (planId === "individual" || planId === "professional" || planId === "research_lab" || planId === "advisory") return LEGACY_PLAN_ALIASES[planId];
  return "free";
}

const launchPlans: Record<LaunchPlanId, EntitlementTemplate> = {
  free: {
    plan_id: "free",
    analyses_per_month: 3,
    max_upload_file_size_mb: 10,
    can_upload_trade_csv: true,
    can_upload_bundle: false,
    can_upload_research_bundle: false,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_prop_evaluation: true,
    can_view_execution: false,
    can_view_regimes: false,
    can_view_stability: false,
    can_view_full_report: false,
    can_export_report: false,
    can_create_share_links: false,
    share_links_per_month: 0,
    can_request_research_desk: false,
    max_seats: 1,
    programs_limit: 1,
    active_hypotheses_limit: 2,
    queued_experiments_limit: 2,
    concurrent_experiments_limit: 1,
    monthly_experiment_compute_units: 10,
    monthly_assistant_calls: 10,
    prop_evaluation_profiles: 0,
    history_retention_days: 30,
    memory_retention_days: 30,
    processing_priority: "standard",
    consulting_cta_variant: "soft",
  },
  explorer: {
    plan_id: "explorer",
    analyses_per_month: 25,
    max_upload_file_size_mb: 25,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: false,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_prop_evaluation: true,
    can_view_execution: true,
    can_view_regimes: false,
    can_view_stability: false,
    can_view_full_report: true,
    can_export_report: true,
    can_create_share_links: true,
    share_links_per_month: 5,
    can_request_research_desk: false,
    max_seats: 1,
    programs_limit: 3,
    active_hypotheses_limit: 10,
    queued_experiments_limit: 12,
    concurrent_experiments_limit: 1,
    monthly_experiment_compute_units: 80,
    monthly_assistant_calls: 100,
    prop_evaluation_profiles: 1,
    history_retention_days: 365,
    memory_retention_days: 365,
    processing_priority: "priority",
    consulting_cta_variant: "serious",
  },
  pro: {
    plan_id: "pro",
    analyses_per_month: 100,
    max_upload_file_size_mb: 50,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: true,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_prop_evaluation: true,
    can_view_execution: true,
    can_view_regimes: false,
    can_view_stability: false,
    can_view_full_report: true,
    can_export_report: true,
    can_create_share_links: true,
    share_links_per_month: 25,
    can_request_research_desk: true,
    max_seats: 1,
    programs_limit: 10,
    active_hypotheses_limit: 40,
    queued_experiments_limit: 40,
    concurrent_experiments_limit: 2,
    monthly_experiment_compute_units: 250,
    monthly_assistant_calls: 500,
    prop_evaluation_profiles: "unlimited",
    history_retention_days: 730,
    memory_retention_days: 730,
    processing_priority: "premium",
    consulting_cta_variant: "institutional",
  },
  team: {
    plan_id: "team",
    analyses_per_month: 250,
    max_upload_file_size_mb: 100,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: true,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_prop_evaluation: true,
    can_view_execution: true,
    can_view_regimes: true,
    can_view_stability: true,
    can_view_full_report: true,
    can_export_report: true,
    can_create_share_links: true,
    share_links_per_month: 75,
    can_request_research_desk: true,
    max_seats: 5,
    programs_limit: 25,
    active_hypotheses_limit: 100,
    queued_experiments_limit: 80,
    concurrent_experiments_limit: 4,
    monthly_experiment_compute_units: 600,
    monthly_assistant_calls: 1500,
    prop_evaluation_profiles: "shared",
    history_retention_days: 1095,
    memory_retention_days: 1095,
    processing_priority: "institutional",
    consulting_cta_variant: "institutional",
  },
  research_desk: {
    plan_id: "research_desk",
    analyses_per_month: 250,
    max_upload_file_size_mb: 250,
    can_upload_trade_csv: true,
    can_upload_bundle: true,
    can_upload_research_bundle: true,
    can_view_overview: true,
    can_view_distribution: true,
    can_view_monte_carlo: true,
    can_view_ruin: true,
    can_view_prop_evaluation: true,
    can_view_execution: true,
    can_view_regimes: true,
    can_view_stability: true,
    can_view_full_report: true,
    can_export_report: true,
    can_create_share_links: true,
    share_links_per_month: 75,
    can_request_research_desk: true,
    max_seats: 10,
    programs_limit: 50,
    active_hypotheses_limit: 250,
    queued_experiments_limit: 100,
    concurrent_experiments_limit: 6,
    monthly_experiment_compute_units: 1000,
    monthly_assistant_calls: 3000,
    prop_evaluation_profiles: "shared",
    history_retention_days: 1825,
    memory_retention_days: 1825,
    processing_priority: "institutional",
    consulting_cta_variant: "institutional",
  },
};

function aliasTemplate(alias: LegacyPlanId): EntitlementTemplate {
  const canonical = launchPlans[LEGACY_PLAN_ALIASES[alias]];
  return { ...canonical, plan_id: alias };
}

export const PLAN_MATRIX: Record<PlanId, EntitlementTemplate> = {
  ...launchPlans,
  individual: aliasTemplate("individual"),
  professional: aliasTemplate("professional"),
  research_lab: aliasTemplate("research_lab"),
  advisory: aliasTemplate("advisory"),
};
