import { getDb } from "@/lib/server/persistence/database";
import { getDatabaseProvider } from "@/lib/server/persistence/provider";
import { getPostgresPool, withPostgresTransaction } from "@/lib/server/persistence/postgres";
import type { C3ProgramDetail, DeploymentCommand, DeploymentProjection, ExchangeConnectorSecret, StrategyDeployment } from "./models";

const iso=(v:unknown)=>v instanceof Date?v.toISOString():String(v);
const json=<T>(v:unknown,f:T):T=>v==null?f:(typeof v==="string"?JSON.parse(v):v) as T;
async function rows(pg:string,sq:string,p:unknown[]){return getDatabaseProvider()==="postgres"?(await getPostgresPool().query(pg,p)).rows as Record<string,unknown>[]:getDb().prepare(sq).all(...p) as Record<string,unknown>[];}
async function run(pg:string,sq:string,p:unknown[]){if(getDatabaseProvider()==="postgres")await getPostgresPool().query(pg,p);else getDb().prepare(sq).run(...p);}
function connector(r:Record<string,unknown>,secret=false):ExchangeConnectorSecret {return {connector_id:String(r.connector_id),account_id:String(r.account_id),created_by_user_id:String(r.created_by_user_id),venue:r.venue as never,environment:r.environment as never,product_type:String(r.product_type??"perpetual") as never,label:String(r.label),status:r.status as never,credential_ciphertext:secret?String(r.credential_ciphertext):"",credential_key_version:secret?String(r.credential_key_version):"",api_key_hint:String(r.api_key_hint),permissions:json(r.permissions_json,{}),doctor:json(r.doctor_json,{}),last_checked_at:r.last_checked_at?iso(r.last_checked_at):undefined,last_used_at:r.last_used_at?iso(r.last_used_at):undefined,revoked_at:r.revoked_at?iso(r.revoked_at):undefined,created_at:iso(r.created_at),updated_at:iso(r.updated_at)};}
function deployment(r:Record<string,unknown>):StrategyDeployment{return {deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),connector_id:String(r.connector_id),qualification_id:String(r.qualification_id),venue:r.venue as never,environment:r.environment as never,product_type:String(r.product_type??"perpetual") as never,status:r.status as never,symbols:json(r.symbols_json,[]),strategy_spec_hash:String(r.strategy_spec_hash),risk_policy_hash:String(r.risk_policy_hash),config_hash:String(r.config_hash),risk_policy:json(r.risk_policy_json,{}),live_canary_approved:Boolean(r.live_canary_approved),created_by_user_id:String(r.created_by_user_id),approved_by_user_id:r.approved_by_user_id?String(r.approved_by_user_id):undefined,approved_at:r.approved_at?iso(r.approved_at):undefined,last_heartbeat_at:r.last_heartbeat_at?iso(r.last_heartbeat_at):undefined,last_reconciled_at:r.last_reconciled_at?iso(r.last_reconciled_at):undefined,frozen_reason:r.frozen_reason?String(r.frozen_reason):undefined,started_at:r.started_at?iso(r.started_at):undefined,stopped_at:r.stopped_at?iso(r.stopped_at):undefined,created_at:iso(r.created_at),updated_at:iso(r.updated_at)};}
function command(r:Record<string,unknown>):DeploymentCommand{return {command_id:String(r.command_id),deployment_id:String(r.deployment_id),program_id:String(r.program_id),account_id:String(r.account_id),command_type:r.command_type as never,status:r.status as never,idempotency_key:String(r.idempotency_key),payload:json(r.payload_json,{}),requested_by_user_id:String(r.requested_by_user_id),available_at:iso(r.available_at),leased_until:r.leased_until?iso(r.leased_until):undefined,attempt_count:Number(r.attempt_count),max_attempts:Number(r.max_attempts),error_code:r.error_code?String(r.error_code):undefined,created_at:iso(r.created_at),processed_at:r.processed_at?iso(r.processed_at):undefined};}
function projection(r:Record<string,unknown>):DeploymentProjection{return {deployment_id:String(r.deployment_id),account_id:String(r.account_id),health:json(r.health_json,{}),balances:json(r.balances_json,{}),positions:json(r.positions_json,[]),orders:json(r.orders_json,[]),fills:json(r.fills_json,[]),incidents:json(r.incidents_json,[]),snapshot_hash:String(r.snapshot_hash),updated_at:iso(r.updated_at)};}

export const c3Repository={
  async detail(programId:string,accountId:string):Promise<C3ProgramDetail>{const p=[programId,accountId];const [c,d,m,e,x]=await Promise.all([
    rows("SELECT * FROM exchange_connectors WHERE account_id=$2 AND revoked_at IS NULL ORDER BY created_at DESC","SELECT * FROM exchange_connectors WHERE account_id=? AND revoked_at IS NULL ORDER BY created_at DESC",getDatabaseProvider()==="postgres"?p:[accountId]),
    rows("SELECT * FROM strategy_deployments WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC","SELECT * FROM strategy_deployments WHERE program_id=? AND account_id=? ORDER BY created_at DESC",p),
    rows("SELECT * FROM deployment_commands WHERE program_id=$1 AND account_id=$2 ORDER BY created_at DESC LIMIT 100","SELECT * FROM deployment_commands WHERE program_id=? AND account_id=? ORDER BY created_at DESC LIMIT 100",p),
    rows("SELECT * FROM deployment_events WHERE program_id=$1 AND account_id=$2 ORDER BY occurred_at DESC LIMIT 200","SELECT * FROM deployment_events WHERE program_id=? AND account_id=? ORDER BY occurred_at DESC LIMIT 200",p),
    rows("SELECT p.* FROM deployment_projections p JOIN strategy_deployments d ON d.deployment_id=p.deployment_id WHERE d.program_id=$1 AND p.account_id=$2","SELECT p.* FROM deployment_projections p JOIN strategy_deployments d ON d.deployment_id=p.deployment_id WHERE d.program_id=? AND p.account_id=?",p),
  ]);return {connectors:c.map(r=>{const v=connector(r);delete (v as Partial<ExchangeConnectorSecret>).credential_ciphertext;delete (v as Partial<ExchangeConnectorSecret>).credential_key_version;return v;}),deployments:d.map(deployment),commands:m.map(command),events:e.map(r=>({...r,payload:json(r.payload_json,{})})),projections:x.map(projection)};},
  async findConnector(id:string,accountId:string,includeSecret=false){const r=await rows("SELECT * FROM exchange_connectors WHERE connector_id=$1 AND account_id=$2","SELECT * FROM exchange_connectors WHERE connector_id=? AND account_id=?",[id,accountId]);return r[0]?connector(r[0],includeSecret):undefined;},
  async insertConnector(v:ExchangeConnectorSecret){await run("INSERT INTO exchange_connectors VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13,$14,$15,$16,$17,$18)","INSERT INTO exchange_connectors VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[v.connector_id,v.account_id,v.created_by_user_id,v.venue,v.environment,v.label,v.status,v.credential_ciphertext,v.credential_key_version,v.api_key_hint,JSON.stringify(v.permissions),JSON.stringify(v.doctor),v.last_checked_at??null,v.last_used_at??null,v.revoked_at??null,v.created_at,v.updated_at,v.product_type]);return v;},
  async updateConnectorDoctor(id:string,accountId:string,status:string,doctor:Record<string,unknown>){const now=new Date().toISOString();await run("UPDATE exchange_connectors SET status=$3,doctor_json=$4::jsonb,last_checked_at=$5,updated_at=$5 WHERE connector_id=$1 AND account_id=$2","UPDATE exchange_connectors SET status=?,doctor_json=?,last_checked_at=?,updated_at=? WHERE connector_id=? AND account_id=?",getDatabaseProvider()==="postgres"?[id,accountId,status,JSON.stringify(doctor),now]:[status,JSON.stringify(doctor),now,now,id,accountId]);},
  async replaceConnectorCredentials(id:string,accountId:string,ciphertext:string,hint:string){const now=new Date().toISOString();await run("UPDATE exchange_connectors SET credential_ciphertext=$3,api_key_hint=$4,status='pending',doctor_json=$5::jsonb,last_checked_at=NULL,updated_at=$6 WHERE connector_id=$1 AND account_id=$2","UPDATE exchange_connectors SET credential_ciphertext=?,api_key_hint=?,status='pending',doctor_json=?,last_checked_at=NULL,updated_at=? WHERE connector_id=? AND account_id=?",getDatabaseProvider()==="postgres"?[id,accountId,ciphertext,hint,JSON.stringify({status:"queued",message:"Replacement credentials are waiting for validation."}),now]:[ciphertext,hint,JSON.stringify({status:"queued",message:"Replacement credentials are waiting for validation."}),now,id,accountId]);},
  async revokeConnector(id:string,accountId:string){const now=new Date().toISOString();await run("UPDATE exchange_connectors SET status='revoked',revoked_at=$3,updated_at=$3 WHERE connector_id=$1 AND account_id=$2","UPDATE exchange_connectors SET status='revoked',revoked_at=?,updated_at=? WHERE connector_id=? AND account_id=?",getDatabaseProvider()==="postgres"?[id,accountId,now]:[now,now,id,accountId]);await run("UPDATE strategy_deployments SET status='frozen',frozen_reason='connector_revoked',updated_at=$3 WHERE connector_id=$1 AND account_id=$2 AND status IN ('queued','starting','active','paused')","UPDATE strategy_deployments SET status='frozen',frozen_reason='connector_revoked',updated_at=? WHERE connector_id=? AND account_id=? AND status IN ('queued','starting','active','paused')",getDatabaseProvider()==="postgres"?[id,accountId,now]:[now,id,accountId]);},
  async insertDeployment(v:StrategyDeployment){const p=[v.deployment_id,v.program_id,v.account_id,v.connector_id,v.qualification_id,v.venue,v.environment,v.status,JSON.stringify(v.symbols),v.strategy_spec_hash,v.risk_policy_hash,v.config_hash,JSON.stringify(v.risk_policy),v.live_canary_approved,v.created_by_user_id,v.approved_by_user_id??null,v.approved_at??null,v.last_heartbeat_at??null,v.last_reconciled_at??null,v.frozen_reason??null,v.started_at??null,v.stopped_at??null,v.created_at,v.updated_at,v.product_type];await run(`INSERT INTO strategy_deployments VALUES (${p.map((_,i)=>`$${i+1}`).join(",")})`,`INSERT INTO strategy_deployments VALUES (${p.map(()=>"?").join(",")})`,p);return v;},
  async findDeployment(id:string,accountId?:string){const p=accountId?[id,accountId]:[id];const r=await rows(accountId?"SELECT * FROM strategy_deployments WHERE deployment_id=$1 AND account_id=$2":"SELECT * FROM strategy_deployments WHERE deployment_id=$1",accountId?"SELECT * FROM strategy_deployments WHERE deployment_id=? AND account_id=?":"SELECT * FROM strategy_deployments WHERE deployment_id=?",p);return r[0]?deployment(r[0]):undefined;},
  async insertCommand(v:DeploymentCommand){const p=[v.command_id,v.deployment_id,v.program_id,v.account_id,v.command_type,v.status,v.idempotency_key,JSON.stringify(v.payload),v.requested_by_user_id,v.available_at,v.leased_until??null,v.attempt_count,v.max_attempts,v.error_code??null,v.created_at,v.processed_at??null];await run(`INSERT INTO deployment_commands VALUES (${p.map((_,i)=>`$${i+1}`).join(",")})`,`INSERT INTO deployment_commands VALUES (${p.map(()=>"?").join(",")})`,p);return v;},
  async findCommandByIdempotencyKey(key:string,accountId:string){const r=await rows("SELECT * FROM deployment_commands WHERE idempotency_key=$1 AND account_id=$2","SELECT * FROM deployment_commands WHERE idempotency_key=? AND account_id=?",[key,accountId]);return r[0]?command(r[0]):undefined;},
  async claimCommand(leaseMs:number):Promise<DeploymentCommand|undefined>{const now=new Date(),until=new Date(now.getTime()+leaseMs).toISOString();if(getDatabaseProvider()==="postgres")return withPostgresTransaction(async client=>{const found=await client.query("SELECT * FROM deployment_commands WHERE status='queued' AND available_at<=NOW() AND (leased_until IS NULL OR leased_until<NOW()) ORDER BY created_at ASC FOR UPDATE SKIP LOCKED LIMIT 1");if(!found.rows[0])return undefined;await client.query("UPDATE deployment_commands SET status='processing',leased_until=$2,attempt_count=attempt_count+1 WHERE command_id=$1",[found.rows[0].command_id,until]);return command({...found.rows[0],status:"processing",leased_until:until,attempt_count:Number(found.rows[0].attempt_count)+1});});const found=getDb().prepare("SELECT * FROM deployment_commands WHERE status='queued' AND available_at<=? AND (leased_until IS NULL OR leased_until<?) ORDER BY created_at ASC LIMIT 1").get(now.toISOString(),now.toISOString());if(!found)return undefined;getDb().prepare("UPDATE deployment_commands SET status='processing',leased_until=?,attempt_count=attempt_count+1 WHERE command_id=?").run(until,found.command_id);return command({...found,status:"processing",leased_until:until,attempt_count:Number(found.attempt_count)+1});},
  async completeCommand(id:string,status:"completed"|"failed",error?:string){const now=new Date().toISOString();await run("UPDATE deployment_commands SET status=$2,error_code=$3,processed_at=$4,leased_until=NULL WHERE command_id=$1","UPDATE deployment_commands SET status=?,error_code=?,processed_at=?,leased_until=NULL WHERE command_id=?",getDatabaseProvider()==="postgres"?[id,status,error??null,now]:[status,error??null,now,id]);},
  async updateDeployment(id:string,status:string,patch:{heartbeat?:string;reconciled?:string;frozenReason?:string|null;started?:string;stopped?:string}){const now=new Date().toISOString();await run("UPDATE strategy_deployments SET status=$2,last_heartbeat_at=COALESCE($3,last_heartbeat_at),last_reconciled_at=COALESCE($4,last_reconciled_at),frozen_reason=$5,started_at=COALESCE($6,started_at),stopped_at=COALESCE($7,stopped_at),updated_at=$8 WHERE deployment_id=$1","UPDATE strategy_deployments SET status=?,last_heartbeat_at=COALESCE(?,last_heartbeat_at),last_reconciled_at=COALESCE(?,last_reconciled_at),frozen_reason=?,started_at=COALESCE(?,started_at),stopped_at=COALESCE(?,stopped_at),updated_at=? WHERE deployment_id=?",getDatabaseProvider()==="postgres"?[id,status,patch.heartbeat??null,patch.reconciled??null,patch.frozenReason??null,patch.started??null,patch.stopped??null,now]:[status,patch.heartbeat??null,patch.reconciled??null,patch.frozenReason??null,patch.started??null,patch.stopped??null,now,id]);},
  async upsertProjection(v:DeploymentProjection){const p=[v.deployment_id,v.account_id,JSON.stringify(v.health),JSON.stringify(v.balances),JSON.stringify(v.positions),JSON.stringify(v.orders),JSON.stringify(v.fills),JSON.stringify(v.incidents),v.snapshot_hash,v.updated_at];await run("INSERT INTO deployment_projections VALUES ($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9,$10) ON CONFLICT(deployment_id) DO UPDATE SET health_json=EXCLUDED.health_json,balances_json=EXCLUDED.balances_json,positions_json=EXCLUDED.positions_json,orders_json=EXCLUDED.orders_json,fills_json=EXCLUDED.fills_json,incidents_json=EXCLUDED.incidents_json,snapshot_hash=EXCLUDED.snapshot_hash,updated_at=EXCLUDED.updated_at","INSERT INTO deployment_projections VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(deployment_id) DO UPDATE SET health_json=excluded.health_json,balances_json=excluded.balances_json,positions_json=excluded.positions_json,orders_json=excluded.orders_json,fills_json=excluded.fills_json,incidents_json=excluded.incidents_json,snapshot_hash=excluded.snapshot_hash,updated_at=excluded.updated_at",p);},
  async insertEvent(v:{id:string;deploymentId:string;programId:string;accountId:string;type:string;idempotencyKey:string;correlationId:string;causationId?:string;payload:Record<string,unknown>;occurredAt:string}){await run("INSERT INTO deployment_events VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) ON CONFLICT(idempotency_key) DO NOTHING","INSERT OR IGNORE INTO deployment_events VALUES (?,?,?,?,?,?,?,?,?,?,?)",[v.id,v.deploymentId,v.programId,v.accountId,v.type,v.idempotencyKey,v.correlationId,v.causationId??null,JSON.stringify(v.payload),v.occurredAt,new Date().toISOString()]);},
  async nextPendingConnector(){const r=await rows("SELECT * FROM exchange_connectors WHERE status='pending' AND revoked_at IS NULL ORDER BY created_at ASC LIMIT 1","SELECT * FROM exchange_connectors WHERE status='pending' AND revoked_at IS NULL ORDER BY created_at ASC LIMIT 1",[]);return r[0]?connector(r[0],true):undefined;},
  async nextActiveDeployment(staleBefore:string){const r=await rows("SELECT * FROM strategy_deployments WHERE status IN ('active','starting') AND (last_heartbeat_at IS NULL OR last_heartbeat_at<$1) ORDER BY COALESCE(last_heartbeat_at,created_at) ASC LIMIT 1","SELECT * FROM strategy_deployments WHERE status IN ('active','starting') AND (last_heartbeat_at IS NULL OR last_heartbeat_at<?) ORDER BY COALESCE(last_heartbeat_at,created_at) ASC LIMIT 1",[staleBefore]);return r[0]?deployment(r[0]):undefined;},
};
