"use client";
import { useMemo, useState } from "react";

type Video = { id:string; title:string; description:string; youtube_url:string; category:string; episode_number:number; duration:string|null; thumbnail:string|null };
const TRACKS = [{key:"all",label:"All Episodes"},{key:"strategy_foundations",label:"Strategy Foundations"},{key:"execution_microstructure",label:"Execution & Microstructure"},{key:"robustness_risk",label:"Robustness & Risk"},{key:"research_workflow",label:"Research Workflow"},{key:"advanced_diagnostics",label:"Advanced Diagnostics"}];
export function ResearchVideoLibrary({ videos }:{videos:Video[]}){ const [track,setTrack]=useState('all'); const [active,setActive]=useState<Video|null>(null); const filtered=useMemo(()=>track==='all'?videos:videos.filter(v=>v.category===track),[track,videos]);
  const counts=(key:string)=> key==='all'?videos.length:videos.filter(v=>v.category===key).length;
  return <div className="grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="space-y-2">{TRACKS.map(t=><button key={t.key} onClick={()=>setTrack(t.key)} className={`flex w-full items-center justify-between rounded-sm border px-3 py-2 text-left text-sm ${track===t.key?"border-brand bg-brand/5 text-brand":"border-border-subtle"}`}><span>{t.label}</span><span className="text-xs text-text-neutral">{counts(t.key)}</span></button>)}</aside><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(v=><article key={v.id} className="rounded-sm border border-border-subtle bg-surface-white"><div className="h-1 w-full bg-brand"/><img src={v.thumbnail ?? '/overlay_graphic.png'} alt="" className="h-40 w-full object-cover" /><div className="space-y-2 p-4"><p className="text-xs uppercase tracking-wide text-text-neutral">Episode {v.episode_number} · {v.category.replaceAll('_',' ')}</p><h3 className="text-base font-semibold">{v.title}</h3><p className="line-clamp-2 text-sm text-text-neutral">{v.description}</p>{v.duration?<p className="text-xs text-text-neutral">{v.duration}</p>:null}<button onClick={()=>setActive(v)} className="rounded-sm border border-brand px-3 py-2 text-sm text-brand hover:bg-brand hover:text-white">Watch Episode</button></div></article>)}{filtered.length===0?<p className="text-sm text-text-neutral">Published episodes will appear here.</p>:null}</div>{active?<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" onClick={()=>setActive(null)}><div className="w-full max-w-4xl rounded-sm bg-surface-white p-4" onClick={(e)=>e.stopPropagation()}><button className="mb-2 text-sm" onClick={()=>setActive(null)}>Close</button><div className="aspect-video"><iframe className="h-full w-full" src={`https://www.youtube.com/embed/${active.youtube_url.match(/(?:v=|youtu\.be\/|embed\/)([A-Za-z0-9_-]{11})/)?.[1] ?? ''}`} allowFullScreen /></div><h4 className="mt-3 font-semibold">{active.title}</h4><p className="text-sm text-text-neutral">{active.description}</p></div></div>:null}</div>
}
