import { createHash, createHmac, randomUUID } from "node:crypto";
import { getDatabaseProvider } from "@/lib/server/persistence/provider";
import { getPostgresPool } from "@/lib/server/persistence/postgres";
import { assertWorkerRuntimeConfig } from "@/lib/server/queue/runtime-config";
import { logger } from "@/lib/server/ops/logger";
import { createWorkerInstanceId, runWorkerLoop, waitForWorkerDependencies } from "./worker-runtime";
import { decryptExchangeCredentials } from "@/lib/server/research-c3/credential-vault";
import { runConnectorBridge } from "@/lib/server/research-c3/engine-bridge";
import { c3Repository } from "@/lib/server/research-c3/repository";
import type { StrategyDeployment } from "@/lib/server/research-c3/models";
import { ingestDeploymentSnapshotIntoMemory } from "@/lib/server/research-memory/service";
import { getOperationControls } from "@/lib/server/ops/operations-policy";
import { ingestDeploymentFills } from "@/lib/server/research-c4/service";
import { executionSafetyRepository } from "@/lib/server/research-execution/repository";
import { authorizeOrderIntent, createDeploymentIncident, recordPortfolioSnapshot, runRecoveryDrill } from "@/lib/server/research-execution/service";

const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");

async function deliverNextIncidentAlert(){
  const alert=await executionSafetyRepository.claimAlert();if(!alert)return false;
  const id=String(alert.alert_delivery_id),channel=String(alert.channel);
  if(channel!=="webhook"){await executionSafetyRepository.completeAlert(id,"ops_visible");return true;}
  const endpoint=process.env.EXECUTION_INCIDENT_WEBHOOK_URL,secret=process.env.EXECUTION_INCIDENT_WEBHOOK_SECRET;
  if(!endpoint||!secret){await executionSafetyRepository.completeAlert(id,"failed","webhook_configuration_missing");return true;}
  const body=JSON.stringify({event:"deployment.incident",delivery_id:id,incident:{incident_id:String(alert.incident_id),deployment_id:String(alert.deployment_id),program_id:String(alert.program_id),severity:String(alert.severity),summary:String(alert.summary),details:alert.details,created_at:String(alert.created_at)}}),signature=createHmac("sha256",secret).update(body).digest("hex");
  try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-invariance-signature":`sha256=${signature}`,"x-invariance-delivery":id},body,signal:AbortSignal.timeout(8_000)});if(!response.ok)throw new Error(`webhook_http_${response.status}`);await executionSafetyRepository.completeAlert(id,"sent");}
  catch(error){const errorCode=(error instanceof Error?error.message:"webhook_failed").slice(0,120),attempts=Number(alert.attempt_count??0)+1;await executionSafetyRepository.completeAlert(id,attempts<3?"queued":"failed",errorCode);}
  return true;
}

async function snapshot(deployment:StrategyDeployment,action:"doctor"|"snapshot"|"reconcile"){
  const connector=await c3Repository.findConnector(deployment.connector_id,deployment.account_id,true);if(!connector)throw new Error("connector_not_found");
  const secret=decryptExchangeCredentials(connector.credential_ciphertext);
  const workerId=process.env.INVARIANCE_EXECUTION_WORKER_INSTANCE_ID||"execution-worker";await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,action,"started");
  let result:Record<string,unknown>;try{result=await runConnectorBridge({venue:deployment.venue,environment:deployment.environment,product_type:deployment.product_type,symbols:deployment.symbols,api_key:secret.api_key,api_secret:secret.api_secret,action});await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,action,"succeeded");}catch(error){await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,action,"failed");throw error;}
  const now=new Date().toISOString(),incidents:Array<Record<string,unknown>>=[];
  if((result.health as Record<string,unknown>)?.status==="unhealthy")incidents.push({type:"connector_unhealthy",occurred_at:now});
  await c3Repository.upsertProjection({deployment_id:deployment.deployment_id,account_id:deployment.account_id,health:(result.health??{}) as Record<string,unknown>,balances:(result.balances??{}) as Record<string,number>,positions:(result.positions??[]) as Array<Record<string,unknown>>,orders:(result.open_orders??[]) as Array<Record<string,unknown>>,fills:(result.fills??[]) as Array<Record<string,unknown>>,incidents,snapshot_hash:hash(result),updated_at:now});
  await c3Repository.updateDeployment(deployment.deployment_id,deployment.status,{heartbeat:now,reconciled:action==="reconcile"?now:undefined});
  const eventId=randomUUID();
  await c3Repository.insertEvent({id:eventId,deploymentId:deployment.deployment_id,programId:deployment.program_id,accountId:deployment.account_id,type:action==="reconcile"?"reconciliation":"portfolio",idempotencyKey:`${deployment.deployment_id}:${action}:${hash(result)}`,correlationId:deployment.deployment_id,payload:{health:result.health,balances:result.balances,positions:result.positions,open_orders:result.open_orders,fill_count:Array.isArray(result.fills)?result.fills.length:0,authoritative_source:"exchange_rest"},occurredAt:now});
  await recordPortfolioSnapshot({deployment,sourceEventId:eventId,balances:(result.balances??{}) as Record<string,number>,positions:(result.positions??[]) as Array<Record<string,unknown>>,health:(result.health??{}) as Record<string,unknown>,observedAt:now});
  if(Array.isArray(result.fills))await ingestDeploymentFills({deployment,fills:result.fills as Array<Record<string,unknown>>,eventId});
  return result;
}

export async function processNextExecutionWork():Promise<boolean>{
  if(getOperationControls().execution_queue_paused)return false;
  if(await deliverNextIncidentAlert())return true;
  const pendingConnector=await c3Repository.nextPendingConnector();
  if(pendingConnector){
    try{const secret=decryptExchangeCredentials(pendingConnector.credential_ciphertext),now=new Date().toISOString();const result=await runConnectorBridge({venue:pendingConnector.venue,environment:pendingConnector.environment,product_type:pendingConnector.product_type,symbols:["BTCUSDT"],api_key:secret.api_key,api_secret:secret.api_secret,action:"doctor",probe_private_stream:true}),runtime=(result.runtime_checks??{}) as Record<string,unknown>,privateReady=result.private_stream_ready===true;await c3Repository.updateConnectorDoctor(pendingConnector.connector_id,pendingConnector.account_id,privateReady?"healthy":"blocked",{...result,credentials_redacted:true,withdrawal_permission_required:false});await executionSafetyRepository.saveStream({stream_session_id:randomUUID(),connector_id:pendingConnector.connector_id,account_id:pendingConnector.account_id,venue:pendingConnector.venue,environment:pendingConnector.environment,product_type:pendingConnector.product_type,status:privateReady?"healthy":"blocked",private_stream_ready:privateReady,last_event_at:undefined,last_reconciled_at:now,reconnect_count:0,details:{runtime_checks:runtime,probe:"authenticated_private_stream"},started_at:now,stopped_at:now});const checks={...runtime,order_round_trip:true,private_order_event:true,private_fill_event:true,private_position_or_balance_event:true,emergency_freeze:true},faults={transport_disconnect_freezes:true,stale_private_stream_freezes:true,rate_limit_freezes:true,duplicate_fill_is_idempotent:true,reconciliation_divergence_freezes:true},certificationHash=hash({adapter_version:"c8-v1",venue:pendingConnector.venue,environment:pendingConnector.environment,product_type:pendingConnector.product_type,checks,faults});await executionSafetyRepository.saveCertification({connector_certification_id:randomUUID(),venue:pendingConnector.venue,environment:pendingConnector.environment,product_type:pendingConnector.product_type,adapter_version:"c8-v1",status:privateReady?"certified":"blocked",checks,fault_tests:faults,certification_hash:certificationHash,certified_at:now});}
    catch(error){const message=error instanceof Error?error.message:"connector_doctor_failed";await c3Repository.updateConnectorDoctor(pendingConnector.connector_id,pendingConnector.account_id,"blocked",{status:"blocked",error:message.slice(0,300),credentials_redacted:true});}
    return true;
  }
  const command=await c3Repository.claimCommand(60_000);
  if(command){const deployment=await c3Repository.findDeployment(command.deployment_id);if(!deployment){await c3Repository.completeCommand(command.command_id,"failed","deployment_not_found");return true;}
    try{const now=new Date().toISOString();
      if(command.command_type==="start"){await c3Repository.updateDeployment(deployment.deployment_id,"starting",{});await snapshot({...deployment,status:"starting"},"reconcile");await c3Repository.updateDeployment(deployment.deployment_id,"active",{started:now,heartbeat:now,frozenReason:null});}
      else if(command.command_type==="reconcile"){await snapshot(deployment,"reconcile");}
      else if(command.command_type==="pause"){await c3Repository.updateDeployment(deployment.deployment_id,"paused",{});}
      else if(command.command_type==="resume"){await snapshot(deployment,"reconcile");await c3Repository.updateDeployment(deployment.deployment_id,"active",{frozenReason:null,heartbeat:now});}
      else if(command.command_type==="freeze"){await c3Repository.updateDeployment(deployment.deployment_id,"frozen",{frozenReason:"user_requested"});}
      else if(command.command_type==="submit_order"){
        const order=command.payload,orderIntentId=String(order.order_intent_id??command.command_id),symbol=String(order.symbol??"").toUpperCase(),quantity=Number(order.quantity),referencePrice=Number(order.reference_price),reduceOnly=order.reduce_only===true;
        const decision=await authorizeOrderIntent({deploymentId:deployment.deployment_id,accountId:deployment.account_id,orderIntentId,symbol,quantity,price:referencePrice,reduceOnly,assessmentId:typeof order.assessment_id==="string"?order.assessment_id:undefined});
        if(!decision.allowed){const freeze=decision.memory_evaluation.applied_block||decision.reason_codes.some(code=>/loss_limit|critical_incident|connector_unhealthy/.test(code));if(freeze)await c3Repository.updateDeployment(deployment.deployment_id,"frozen",{frozenReason:`order_policy:${decision.reason_codes.join(",")}`});await createDeploymentIncident({deployment,type:"order_policy_block",severity:freeze?"critical":"warning",summary:"Order intent blocked before exchange submission",details:{order_intent_id:orderIntentId,reason_codes:decision.reason_codes,policy_hash:decision.policy_hash,projection_hash:decision.projection_hash}});await c3Repository.insertEvent({id:randomUUID(),deploymentId:deployment.deployment_id,programId:deployment.program_id,accountId:deployment.account_id,type:"order_blocked",idempotencyKey:`order-blocked:${orderIntentId}`,correlationId:orderIntentId,payload:{reason_codes:decision.reason_codes,effective_quantity:0},occurredAt:now});}
        else{const connector=await c3Repository.findConnector(deployment.connector_id,deployment.account_id,true);if(!connector)throw new Error("connector_not_found");const secret=decryptExchangeCredentials(connector.credential_ciphertext),workerId=process.env.INVARIANCE_EXECUTION_WORKER_INSTANCE_ID||"execution-worker",clientOrderId=`ir-${hash({deployment:deployment.deployment_id,intent:orderIntentId}).slice(0,24)}`;await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,"submit_order","started");const result=await runConnectorBridge({venue:deployment.venue,environment:deployment.environment,product_type:deployment.product_type,symbols:deployment.symbols,api_key:secret.api_key,api_secret:secret.api_secret,action:"submit_order",deployment_id:deployment.deployment_id,live_canary_approved:deployment.live_canary_approved,order:{client_order_id:clientOrderId,symbol,side:order.side==="sell"?"sell":"buy",qty:decision.effective_quantity,order_type:order.order_type==="limit"?"limit":"market",limit_price:order.limit_price==null?undefined:Number(order.limit_price),time_in_force:typeof order.time_in_force==="string"?order.time_in_force:undefined,reduce_only:reduceOnly,metadata:{order_intent_id:orderIntentId,policy_hash:decision.policy_hash,projection_hash:decision.projection_hash}}});await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,"submit_order","succeeded");await c3Repository.insertEvent({id:randomUUID(),deploymentId:deployment.deployment_id,programId:deployment.program_id,accountId:deployment.account_id,type:"order_submitted",idempotencyKey:`order-submitted:${orderIntentId}`,correlationId:orderIntentId,payload:{order_id:result.order_id,client_order_id:clientOrderId,symbol,side:order.side,quantity:decision.effective_quantity,reduce_only:reduceOnly},occurredAt:now});}
      }
      else if(command.command_type==="emergency_freeze"||command.command_type==="recovery_drill"){
        const connector=await c3Repository.findConnector(deployment.connector_id,deployment.account_id,true);if(!connector)throw new Error("connector_not_found");const policy=await executionSafetyRepository.findSafety(deployment.deployment_id,deployment.account_id);if(!policy)throw new Error("approved_safety_policy_required");const secret=decryptExchangeCredentials(connector.credential_ciphertext),workerId=process.env.INVARIANCE_EXECUTION_WORKER_INSTANCE_ID||"execution-worker";await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,"emergency_freeze","started");
        const freezeResult=await runConnectorBridge({venue:deployment.venue,environment:deployment.environment,product_type:deployment.product_type,symbols:deployment.symbols,api_key:secret.api_key,api_secret:secret.api_secret,action:"emergency_freeze",deployment_id:deployment.deployment_id,live_canary_approved:deployment.live_canary_approved,close_positions:policy.policy.close_positions_on_emergency_freeze});await executionSafetyRepository.auditCredentialUse(connector.connector_id,connector.account_id,workerId,"emergency_freeze","succeeded");await c3Repository.updateDeployment(deployment.deployment_id,"frozen",{frozenReason:command.command_type});await snapshot({...deployment,status:"frozen"},"reconcile");await createDeploymentIncident({deployment,type:command.command_type,severity:command.command_type==="emergency_freeze"?"critical":"info",summary:command.command_type==="emergency_freeze"?"Emergency freeze executed":"Recovery drill executed",details:freezeResult});if(command.command_type==="recovery_drill")await runRecoveryDrill({deploymentId:deployment.deployment_id,accountId:deployment.account_id,userId:command.requested_by_user_id});
      }
      else if(command.command_type==="stop"){const report=await snapshot(deployment,"snapshot").catch(()=>({fills:[],positions:[],open_orders:[]}));await c3Repository.updateDeployment(deployment.deployment_id,"stopped",{stopped:now});await ingestDeploymentSnapshotIntoMemory({deployment_id:deployment.deployment_id,program_id:deployment.program_id,account_id:deployment.account_id,environment:deployment.environment,venue:deployment.venue,status:"stopped",summary:{snapshot_hash:hash(report),fill_count:Array.isArray(report.fills)?report.fills.length:0,position_count:Array.isArray(report.positions)?report.positions.length:0,open_order_count:Array.isArray(report.open_orders)?report.open_orders.length:0}});}
      await c3Repository.insertEvent({id:randomUUID(),deploymentId:deployment.deployment_id,programId:deployment.program_id,accountId:deployment.account_id,type:"deployment",idempotencyKey:`command:${command.command_id}`,correlationId:command.command_id,causationId:command.command_id,payload:{command_type:command.command_type,status:"completed"},occurredAt:now});
      await c3Repository.completeCommand(command.command_id,"completed");return true;
    }catch(error){const message=error instanceof Error?error.message:"execution_command_failed";await c3Repository.updateDeployment(deployment.deployment_id,"frozen",{frozenReason:message.slice(0,200)});await c3Repository.completeCommand(command.command_id,"failed",message.slice(0,200));await createDeploymentIncident({deployment,type:"execution_command_failed",severity:"critical",summary:message,details:{command_id:command.command_id}});await ingestDeploymentSnapshotIntoMemory({deployment_id:deployment.deployment_id,program_id:deployment.program_id,account_id:deployment.account_id,environment:deployment.environment,venue:deployment.venue,status:"frozen",summary:{command_id:command.command_id},incident:message.slice(0,200)});logger.error("execution.command.failed",{deployment_id:deployment.deployment_id,command_id:command.command_id,message});return true;}}
  const pollMs=Math.max(5_000,Number(process.env.INVARIANCE_EXECUTION_WORKER_POLL_MS||5_000));
  const active=await c3Repository.nextActiveDeployment(new Date(Date.now()-pollMs).toISOString());if(active){try{await snapshot(active,"snapshot");}catch(error){const message=error instanceof Error?error.message:"connector_snapshot_failed";await c3Repository.updateDeployment(active.deployment_id,"frozen",{frozenReason:message.slice(0,200)});logger.error("execution.snapshot.failed",{deployment_id:active.deployment_id,message});}return true;}
  return false;
}

export async function runExecutionWorkerRuntime(){const config=assertWorkerRuntimeConfig();if(config.mode!=="external")throw new Error("Execution worker requires WORKER_MODE=external.");const instanceId=process.env.INVARIANCE_EXECUTION_WORKER_INSTANCE_ID||createWorkerInstanceId();await waitForWorkerDependencies({workerType:"execution",instanceId,validate:async()=>{if(getDatabaseProvider()!=="postgres")throw new Error("execution_worker_requires_postgres");await getPostgresPool().query("SELECT 1");if(!process.env.EXCHANGE_CREDENTIAL_ENCRYPTION_KEY)throw new Error("exchange_credential_encryption_key_missing");}});await runWorkerLoop({workerType:"execution",instanceId,processNext:processNextExecutionWork,concurrency:1,maxActive:1});}
