import { createHash } from "node:crypto";
import type { DecisionStateSnapshot, MemoryAssessment, TradeEpisode } from "./models";

export const hashCanonical=(value:unknown)=>createHash("sha256").update(JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item)).digest("hex");
const finite=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:undefined;
export function validateDecisionState(snapshot:DecisionStateSnapshot){const errors:string[]=[];const decision=Date.parse(snapshot.decision_at),captured=Date.parse(snapshot.captured_at);if(!Number.isFinite(decision)||!Number.isFinite(captured))errors.push("state_snapshot_timestamp_invalid");else if(captured>decision)errors.push("state_snapshot_captured_after_decision");for(const [key,value] of Object.entries(snapshot.features)){if(finite(value)===undefined)errors.push(`state_snapshot_feature_non_finite:${key}`);const ts=Date.parse(snapshot.feature_timestamps[key]??"");if(!Number.isFinite(ts))errors.push(`state_snapshot_feature_timestamp_missing:${key}`);else if(ts>decision)errors.push(`state_snapshot_future_feature:${key}`);}if(snapshot.future_enriched!==false)errors.push("state_snapshot_future_enrichment_forbidden");return errors;}
export function assessMemory(input:{assessmentId:string;accountId:string;programId:string;strategySpecHash:string;current:DecisionStateSnapshot;episodes:TradeEpisode[];snapshots:DecisionStateSnapshot[];now:string;minSupport?:number}):MemoryAssessment{
  const base={schema_version:"memory_assessment_v1" as const,assessment_id:input.assessmentId,account_id:input.accountId,program_id:input.programId,strategy_spec_hash:input.strategySpecHash,current_state_snapshot_id:input.current.state_snapshot_id,uncertainty_interval:[] as number[],calibration:{status:"pending_outcome"},source_episode_ids:[] as string[],missing_state_features:input.current.missing_features,advisory_only:true as const,created_at:input.now};
  const invalid=validateDecisionState(input.current);if(invalid.length||!Object.keys(input.current.features).length)return {...base,assessment:"insufficient_evidence",reason_codes:invalid.length?invalid:["current_state_features_missing"],support_count:0,strategy_support_count:0,cross_strategy_support_count:0};
  const byId=new Map(input.snapshots.map(s=>[s.state_snapshot_id,s])),candidates=input.episodes.flatMap(episode=>{const state=episode.decision_state_snapshot_id?byId.get(episode.decision_state_snapshot_id):undefined;return episode.status==="closed"&&finite(episode.net_pnl)!==undefined&&state&&!validateDecisionState(state).length?[{episode,state}]:[];});
  const keys=Object.keys(input.current.features),scales=Object.fromEntries(keys.map(key=>{const values=candidates.map(c=>c.state.features[key]).filter(v=>finite(v)!==undefined);const avg=values.reduce((a,b)=>a+b,0)/Math.max(values.length,1);return [key,Math.max(Math.sqrt(values.reduce((s,v)=>s+(v-avg)**2,0)/Math.max(values.length,1)),1e-9)];}));
  const currentTime=Date.parse(input.now),comparable=candidates.map(({episode,state})=>{const shared=keys.filter(k=>finite(state.features[k])!==undefined);const distance=shared.length?Math.sqrt(shared.reduce((sum,key)=>sum+((input.current.features[key]-state.features[key])/scales[key])**2,0)/shared.length):Infinity;const age=Math.max(0,(currentTime-Date.parse(episode.closed_at!))/86400000);return {episode,distance,shared:shared.length,weight:Math.exp(-Math.log(2)*age/90)*Math.exp(-distance)};}).filter(x=>x.shared>=Math.max(1,Math.ceil(keys.length*.5))&&x.distance<=2.5).sort((a,b)=>a.distance-b.distance).slice(0,100);
  const min=input.minSupport??8;if(comparable.length<min)return {...base,assessment:"insufficient_evidence",reason_codes:["comparable_support_below_minimum"],support_count:comparable.length,strategy_support_count:comparable.filter(x=>x.episode.strategy_spec_hash===input.strategySpecHash).length,cross_strategy_support_count:comparable.filter(x=>x.episode.strategy_spec_hash!==input.strategySpecHash).length,source_episode_ids:comparable.map(x=>x.episode.episode_id)};
  const total=comparable.reduce((s,x)=>s+x.weight,0),expected=comparable.reduce((s,x)=>s+x.episode.net_pnl!*x.weight,0)/total,positive=comparable.filter(x=>x.episode.net_pnl!>0).reduce((s,x)=>s+x.weight,0)/total,se=Math.sqrt(Math.max(positive*(1-positive),0)/comparable.length),interval=[Math.max(0,positive-1.96*se),Math.min(1,positive+1.96*se)],pnl=comparable.map(x=>x.episode.net_pnl!).sort((a,b)=>a-b),downside=pnl[Math.max(0,Math.ceil(pnl.length*.1)-1)],allDistance=comparable.reduce((s,x)=>s+x.distance,0)/comparable.length,recent=comparable.slice(0,Math.min(10,comparable.length)).reduce((s,x)=>s+x.distance,0)/Math.min(10,comparable.length),drift=recent/Math.max(allDistance,1e-12);
  let assessment:MemoryAssessment["assessment"]="neutral",reason="comparable_outcomes_mixed";if(drift>1.5){assessment="caution";reason="state_drift_elevated";}else if(interval[1]<.45||(expected<0&&downside<0)){assessment="block";reason="comparable_outcomes_adverse";}else if(interval[0]>.55&&expected>0){assessment="supportive";reason="comparable_outcomes_positive";}
  return {...base,assessment,reason_codes:[reason],support_count:comparable.length,strategy_support_count:comparable.filter(x=>x.episode.strategy_spec_hash===input.strategySpecHash).length,cross_strategy_support_count:comparable.filter(x=>x.episode.strategy_spec_hash!==input.strategySpecHash).length,state_similarity_score:1/(1+allDistance),drift_ratio:drift,expected_net_pnl:expected,downside_p10_net_pnl:downside,empirical_positive_rate:positive,uncertainty_interval:interval,source_episode_ids:comparable.map(x=>x.episode.episode_id)};
}
