import { randomUUID } from "node:crypto";
import { hashLifecycleEvent, RESEARCH_LIFECYCLE_VERSION, type ResearchLifecycleEvent } from "@/lib/contracts/research-lifecycle";
import { getDb } from "@/lib/server/persistence/database";
import { getDatabaseProvider } from "@/lib/server/persistence/provider";
import { getPostgresPool } from "@/lib/server/persistence/postgres";
import { getResearchProgramDetail } from "@/lib/server/research-programs/service";
import { c2Repository } from "@/lib/server/research-c2/repository";
import { researchMemoryRepository } from "@/lib/server/research-memory/repository";
import { researchSpecV2Repository } from "@/lib/server/research-specs-v2/repository";
import { assessMemory, hashCanonical, validateDecisionState } from "./assessment";
import { c4Repository } from "./repository";
import type { CanonicalMemoryEntry, DecisionStateSnapshot, ResearchStage, TradeEpisode } from "./models";
import type { StrategyDeployment } from "@/lib/server/research-c3/models";

async function assertProgram(programId:string,accountId:string){const value=await getResearchProgramDetail(programId,accountId);if(!value)throw new Error("program_not_found");return value;}
export async function getC4Detail(programId:string,accountId:string){await assertProgram(programId,accountId);return c4Repository.detail(programId,accountId);}
export async function saveDecisionSnapshot(input:Omit<DecisionStateSnapshot,"schema_version"|"snapshot_hash"|"created_at"|"future_enriched">){
  const body={...input,schema_version:"decision_state_snapshot_v1" as const,future_enriched:false as const},snapshot:DecisionStateSnapshot={...body,snapshot_hash:hashCanonical(body),created_at:new Date().toISOString()};
  const errors=validateDecisionState(snapshot);if(errors.length)throw new Error(`decision_state_invalid:${errors.join(",")}`);return c4Repository.saveSnapshot(snapshot);
}
export async function createMemoryAssessment(input:{programId:string;accountId:string;userId:string;strategySpecHash:string;symbol:string;stage:ResearchStage;features:Record<string,number>;featureTimestamps?:Record<string,string>;missingFeatures?:string[];runId?:string;deploymentId?:string;decisionAt?:string}){
  await assertProgram(input.programId,input.accountId);const now=input.decisionAt??new Date().toISOString(),snapshot=await saveDecisionSnapshot({state_snapshot_id:randomUUID(),account_id:input.accountId,program_id:input.programId,stage:input.stage,strategy_spec_hash:input.strategySpecHash,run_id:input.runId,deployment_id:input.deploymentId,symbol:input.symbol,decision_at:now,captured_at:now,features:input.features,feature_timestamps:input.featureTimestamps??Object.fromEntries(Object.keys(input.features).map(key=>[key,now])),missing_features:input.missingFeatures??[],provenance:{source:"assessment_request",causal_cutoff:now}});
  const evidence=await c4Repository.accountEvidence(input.accountId),assessment=assessMemory({assessmentId:randomUUID(),accountId:input.accountId,programId:input.programId,strategySpecHash:input.strategySpecHash,current:snapshot,episodes:evidence.episodes,snapshots:evidence.snapshots,now});
  await c4Repository.saveAssessment(assessment);
  const event: Omit<ResearchLifecycleEvent,"event_hash">={schema_version:RESEARCH_LIFECYCLE_VERSION,event_id:randomUUID(),event_type:"memory_assessment",occurred_at:now,identity:{program_id:input.programId,account_id:input.accountId,stage:input.stage,strategy_spec_hash:input.strategySpecHash,code_hash:"not_applicable",data_snapshot_id:snapshot.snapshot_hash,...(input.runId?{run_id:input.runId}:{}),...(input.deploymentId?{deployment_id:input.deploymentId}:{})},payload:{memory_item_id:assessment.assessment_id,assessment:assessment.assessment,confidence:assessment.support_count>=8?"evidence_supported":"insufficient_evidence",advisory_only:true,support_count:assessment.support_count,state_snapshot_id:snapshot.state_snapshot_id},actor:{type:"user",id:input.userId}};
  await researchSpecV2Repository.appendLifecycle({...event,event_hash:hashLifecycleEvent(event)});
  return assessment;
}
function number(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined;}
function featureRecord(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return {};return Object.fromEntries(Object.entries(value as Record<string,unknown>).flatMap(([key,raw])=>{const parsed=number(raw);return parsed===undefined?[]:[[key,parsed]];}));}
function objectRecord(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
export async function ingestBacktestTradeMemory(programId:string,accountId:string){
  await assertProgram(programId,accountId);const c2=await c2Repository.detail(programId,accountId),qualification=c2.qualifications.find(q=>q.status==="qualified")??c2.qualifications[0];let created=0,snapshots=0;
  for(const entry of c2.catalog.filter(item=>item.artifact_type==="trades"&&item.status==="ready")){const trades=Array.isArray(entry.query_payload.trades)?entry.query_payload.trades:[];for(let index=0;index<trades.length;index++){const trade=trades[index] as Record<string,unknown>,opened=String(trade.entry_time??""),closed=String(trade.exit_time??""),symbol=String(trade.symbol??"").toUpperCase();if(!opened||!closed||!symbol)continue;const strategyHash=qualification?.strategy_spec_hash??`artifact:${entry.content_hash}`,features=featureRecord(trade.state_features??trade.feature_values),stateId=Object.keys(features).length?randomUUID():undefined;if(stateId){await saveDecisionSnapshot({state_snapshot_id:stateId,account_id:accountId,program_id:programId,stage:"backtest",strategy_spec_hash:strategyHash,run_id:String(entry.lineage.run_id??entry.lineage.analysis_id??entry.object_id),symbol,decision_at:opened,captured_at:opened,features,feature_timestamps:Object.fromEntries(Object.keys(features).map(key=>[key,opened])),missing_features:[],provenance:{catalog_id:entry.catalog_id,row:index+1,content_hash:entry.content_hash}});snapshots++;}
      const gross=number(trade.pnl),fees=number(trade.fees)??0,episode:TradeEpisode={schema_version:"trade_episode_v1",episode_id:`bt_${hashCanonical({catalog:entry.catalog_id,index,trade_id:trade.trade_id}) .slice(0,28)}`,account_id:accountId,program_id:programId,stage:"backtest",run_id:String(entry.lineage.run_id??entry.lineage.analysis_id??entry.object_id),strategy_spec_hash:strategyHash,venue:trade.exchange?String(trade.exchange):undefined,product_type:String(trade.market??"").toLowerCase().includes("spot")?"spot":"perpetual",symbol,side:String(trade.side).toLowerCase()==="short"?"sell":"buy",opened_at:opened,closed_at:closed,quantity:number(trade.quantity)??0,entry_price:number(trade.entry_price),exit_price:number(trade.exit_price),gross_pnl:gross,fees,net_pnl:gross===undefined?undefined:gross-fees,status:"closed",decision_state_snapshot_id:stateId,source_event_ids:[],source_fill_ids:[],data_quality:{source:"artifact_catalog",catalog_id:entry.catalog_id,decision_state:Object.keys(features).length?"available":"missing",future_enriched:false},created_at:new Date().toISOString(),updated_at:new Date().toISOString()};await c4Repository.upsertEpisode(episode);created++;}}
  return {episodes_created:created,state_snapshots_created:snapshots,state_analysis_available:snapshots>0};
}
export async function ingestDeploymentFills(input:{deployment:StrategyDeployment;fills:Array<Record<string,unknown>>;eventId:string}){let processed=0,closed=0;
  for(const fill of [...input.fills].sort((a,b)=>String(a.ts??"").localeCompare(String(b.ts??"")))){const metadata=fill.metadata&&typeof fill.metadata==="object"?fill.metadata as Record<string,unknown>:{},fillId=String(metadata.trade_id??metadata.exec_id??hashCanonical(fill)),identity=`${input.deployment.venue}:${input.deployment.environment}:${input.deployment.product_type}:${fillId}`;if(await c4Repository.fillProcessed(identity))continue;const symbol=String(fill.symbol??"").toUpperCase(),side=String(fill.side??"").toLowerCase()==="sell"?"sell":"buy",qty=Math.abs(number(fill.qty)??0),price=number(fill.price),fee=Math.abs(number(fill.fee)??0),ts=String(fill.ts??new Date().toISOString());if(!symbol||!qty||price===undefined){await c4Repository.recordFill(identity,input.deployment.account_id,input.deployment.program_id,input.deployment.deployment_id,undefined,fill);continue;}
    let stateId: string|undefined;const state=featureRecord(metadata.decision_state??metadata.feature_values);if(Object.keys(state).length){stateId=randomUUID();await saveDecisionSnapshot({state_snapshot_id:stateId,account_id:input.deployment.account_id,program_id:input.deployment.program_id,stage:input.deployment.environment==="live"?"live_canary":"demo",strategy_spec_hash:input.deployment.strategy_spec_hash,deployment_id:input.deployment.deployment_id,symbol,decision_at:String(metadata.decision_at??ts),captured_at:String(metadata.decision_at??ts),features:state,feature_timestamps:Object.fromEntries(Object.keys(state).map(key=>[key,String(metadata.decision_at??ts)])),missing_features:Array.isArray(metadata.missing_features)?metadata.missing_features.map(String):[],provenance:{source:"exchange_fill",fill_identity:identity,future_enriched:false}});}
    const open=await c4Repository.findOpenEpisode(input.deployment.deployment_id,symbol,input.deployment.account_id);if(!open){if(input.deployment.product_type==="spot"&&side==="sell"){await c4Repository.recordFill(identity,input.deployment.account_id,input.deployment.program_id,input.deployment.deployment_id,undefined,{...fill,data_quality:"missing_spot_entry_basis"});continue;}const now=new Date().toISOString(),episode:TradeEpisode={schema_version:"trade_episode_v1",episode_id:randomUUID(),account_id:input.deployment.account_id,program_id:input.deployment.program_id,stage:input.deployment.environment==="live"?"live_canary":"demo",deployment_id:input.deployment.deployment_id,strategy_spec_hash:input.deployment.strategy_spec_hash,venue:input.deployment.venue,environment:input.deployment.environment,product_type:input.deployment.product_type,symbol,side,opened_at:ts,quantity:qty,entry_price:price,fees:fee,status:"open",decision_state_snapshot_id:stateId,source_event_ids:[input.eventId],source_fill_ids:[fillId],data_quality:{source:"exchange_fill",decision_state:stateId?"available":"missing",future_enriched:false},created_at:now,updated_at:now};await c4Repository.upsertEpisode(episode);await c4Repository.recordFill(identity,episode.account_id,episode.program_id,input.deployment.deployment_id,episode.episode_id,fill);processed++;continue;}
    if(open.side===side){const oldQty=open.quantity,newQty=oldQty+qty;open.entry_price=((open.entry_price??price)*oldQty+price*qty)/newQty;open.quantity=newQty;open.fees+=fee;open.source_fill_ids.push(fillId);open.source_event_ids.push(input.eventId);open.updated_at=new Date().toISOString();await c4Repository.upsertEpisode(open);await c4Repository.recordFill(identity,open.account_id,open.program_id,input.deployment.deployment_id,open.episode_id,fill);processed++;continue;}
    const closeQty=Math.min(open.quantity,qty),direction=open.side==="buy"?1:-1,gross=(price-(open.entry_price??price))*closeQty*direction;open.gross_pnl=(open.gross_pnl??0)+gross;open.fees+=fee;open.net_pnl=open.gross_pnl-open.fees;open.exit_price=price;open.quantity-=closeQty;open.source_fill_ids.push(fillId);open.source_event_ids.push(input.eventId);open.updated_at=new Date().toISOString();if(open.quantity<=1e-12){open.quantity=closeQty;open.status="closed";open.closed_at=ts;closed++;}await c4Repository.upsertEpisode(open);if(open.status==="closed")await c4Repository.calibrateForEpisode(open);await c4Repository.recordFill(identity,open.account_id,open.program_id,input.deployment.deployment_id,open.episode_id,fill);processed++;
  }return {fills_processed:processed,episodes_closed:closed};}
async function governedRows(programId:string,accountId:string){if(getDatabaseProvider()==="postgres"){const pool=getPostgresPool();const [notes,decisions,pine,observations]=await Promise.all([pool.query("SELECT * FROM program_notes WHERE program_id=$1 AND account_id=$2",[programId,accountId]),pool.query("SELECT d.*,p.proposal_type,p.title,p.payload_json AS proposal_payload_json,p.content_hash FROM research_decisions d JOIN research_proposals p ON p.proposal_id=d.proposal_id WHERE d.program_id=$1 AND d.account_id=$2 AND d.decision_type IN ('confirmed','rejected')",[programId,accountId]),pool.query("SELECT * FROM pine_parity_results WHERE program_id=$1 AND account_id=$2 AND verdict IN ('verified','pass')",[programId,accountId]),pool.query("SELECT * FROM tradingview_signal_observations WHERE program_id=$1 AND account_id=$2 AND verification_status='matched_engine_signal'",[programId,accountId])]);return {notes:notes.rows,decisions:decisions.rows,pine:pine.rows,observations:observations.rows};}const db=getDb();return {notes:db.prepare("SELECT * FROM program_notes WHERE program_id=? AND account_id=?").all(programId,accountId),decisions:db.prepare("SELECT d.*,p.proposal_type,p.title,p.payload_json AS proposal_payload_json,p.content_hash FROM research_decisions d JOIN research_proposals p ON p.proposal_id=d.proposal_id WHERE d.program_id=? AND d.account_id=? AND d.decision_type IN ('confirmed','rejected')").all(programId,accountId),pine:db.prepare("SELECT * FROM pine_parity_results WHERE program_id=? AND account_id=? AND verdict IN ('verified','pass')").all(programId,accountId),observations:db.prepare("SELECT * FROM tradingview_signal_observations WHERE program_id=? AND account_id=? AND verification_status='matched_engine_signal'").all(programId,accountId)};}
export async function syncGovernedResearchMemory(programId:string,accountId:string){await assertProgram(programId,accountId);const rows=await governedRows(programId,accountId),now=new Date().toISOString(),sources=[...rows.notes.map((row:Record<string,unknown>)=>({type:"confirmed_note",sourceType:"program_note",id:String(row.note_id),status:"confirmed",payload:{note_type:row.note_type,body:row.body},lineage:{author_user_id:row.author_user_id},user:String(row.author_user_id),at:String(row.updated_at)})),...rows.decisions.map((row:Record<string,unknown>)=>({type:row.decision_type==="rejected"?"rejected_hypothesis":"user_decision",sourceType:"research_decision",id:String(row.decision_id),status:String(row.decision_type),payload:{proposal_type:row.proposal_type,title:row.title,proposal:typeof row.proposal_payload_json==="string"?JSON.parse(row.proposal_payload_json):row.proposal_payload_json},lineage:{proposal_id:row.proposal_id,conversation_id:row.conversation_id},user:String(row.actor_user_id),at:String(row.created_at)})),...rows.pine.map((row:Record<string,unknown>)=>({type:"pine_parity",sourceType:"pine_parity_result",id:String(row.parity_result_id),status:"verified",payload:typeof row.report_json==="string"?JSON.parse(row.report_json):row.report_json,lineage:{pine_export_id:row.pine_export_id},at:String(row.created_at)})),...rows.observations.map((row:Record<string,unknown>)=>({type:"verified_tradingview_observation",sourceType:"tradingview_observation",id:String(row.observation_id),status:"verified",payload:typeof row.observation_json==="string"?JSON.parse(row.observation_json):row.observation_json,lineage:{pine_export_id:row.pine_export_id,stage_qualified:true,not_trade_episode:true},at:String(row.received_at)}))];
  for(const source of sources){const contentHash=hashCanonical(source.payload),entry:CanonicalMemoryEntry={canonical_memory_entry_id:randomUUID(),account_id:accountId,program_id:programId,entry_type:source.type,source_type:source.sourceType,source_id:source.id,status:source.status,payload:objectRecord(source.payload),lineage:source.lineage,content_hash:contentHash,confirmed_by_user_id:"user" in source?source.user:undefined,confirmed_at:source.at,created_at:now},payload=objectRecord(source.payload);await c4Repository.saveCanonicalEntry(entry);await researchMemoryRepository.saveBatch({items:[{memory_item_id:`canonical_${hashCanonical({accountId,source:source.id,contentHash}).slice(0,24)}`,account_id:accountId,program_id:programId,memory_type:source.type.includes("pine")||source.type.includes("tradingview")?"pine_lineage":"confirmed_reasoning",title:String(payload.title??source.type.replaceAll("_"," ")),summary:String(payload.body??payload.title??source.status),status:source.status,confidence:1,source_event_id:source.id,source_card_type:source.type,source:{...payload,lineage:source.lineage},tags:[source.type,source.status],created_at:source.at,updated_at:now}],links:[],findings:[],recommendations:[],similar:[]});}
  return {canonical_entries:sources.length,excluded_raw_messages:true,excluded_unconfirmed_proposals:true};}
