import { NextResponse } from "next/server";
import { requireServerSession } from "@/lib/server/auth/session";
import { enforceRateLimit } from "@/lib/server/rate-limits";
import { enqueueDeploymentCommand } from "@/lib/server/research-c3/service";
import { configureMemoryPolicy, configureSafetyPolicy, evaluateDemoToLive, evaluateMemoryPolicyForOrder, getExecutionSafetyDetail, resolveDeploymentIncident, resolveMemoryPolicyEvaluation } from "@/lib/server/research-execution/service";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const session=await requireServerSession(),{id}=await params;return NextResponse.json({detail:await getExecutionSafetyDetail(id,session.account_id)});}

export async function POST(request:Request){
  const session=await requireServerSession(),limited=await enforceRateLimit({request,route:"research_execution",kind:"program_write",userId:session.user_id,accountId:session.account_id});if(limited)return limited;if(Number(request.headers.get("content-length")??0)>64_000)return NextResponse.json({error:{code:"request_too_large",message:"Execution actions are limited to 64 KB."}},{status:413});const body=await request.json().catch(()=>({})) as Record<string,unknown>;
  try{
    if(body.action==="configure_safety")return NextResponse.json({policy:await configureSafetyPolicy({deploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,policy:body.policy&&typeof body.policy==="object"?body.policy as Record<string,unknown>:{},approve:body.approve===true})});
    if(body.action==="evaluate_demo_promotion")return NextResponse.json({promotion:await evaluateDemoToLive({demoDeploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,approve:body.approve===true,minimumClosedTrades:Number(body.minimum_closed_trades??20),minimumDemoDays:Number(body.minimum_demo_days??7)})});
    if(body.action==="recovery_drill")return NextResponse.json({command:await enqueueDeploymentCommand({deploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,commandType:"recovery_drill"})});
    if(body.action==="emergency_freeze")return NextResponse.json({command:await enqueueDeploymentCommand({deploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,commandType:"emergency_freeze",idempotencyKey:`emergency:${String(body.deployment_id)}:${Date.now()}`})});
    if(body.action==="configure_memory_policy")return NextResponse.json({policy:await configureMemoryPolicy({deploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,mode:body.mode==="enforced"?"enforced":"shadow",approve:body.approve===true,thresholds:body.thresholds&&typeof body.thresholds==="object"?body.thresholds as Record<string,unknown>:{}})});
    if(body.action==="evaluate_memory_policy")return NextResponse.json({evaluation:await evaluateMemoryPolicyForOrder({deploymentId:String(body.deployment_id??""),accountId:session.account_id,orderIntentId:String(body.order_intent_id??crypto.randomUUID()),requestedQuantity:Number(body.requested_quantity??0),assessmentId:typeof body.assessment_id==="string"?body.assessment_id:undefined})});
    if(body.action==="submit_order")return NextResponse.json({command:await enqueueDeploymentCommand({deploymentId:String(body.deployment_id??""),accountId:session.account_id,userId:session.user_id,commandType:"submit_order",idempotencyKey:typeof body.idempotency_key==="string"?body.idempotency_key:undefined,payload:{order_intent_id:String(body.order_intent_id??crypto.randomUUID()),symbol:String(body.symbol??""),side:body.side==="sell"?"sell":"buy",quantity:Number(body.quantity??0),reference_price:Number(body.reference_price??0),order_type:body.order_type==="limit"?"limit":"market",limit_price:body.limit_price==null?undefined:Number(body.limit_price),time_in_force:typeof body.time_in_force==="string"?body.time_in_force:undefined,reduce_only:body.reduce_only===true,assessment_id:typeof body.assessment_id==="string"?body.assessment_id:undefined}})});
    if(body.action==="resolve_memory_evaluation")return NextResponse.json({evaluation:await resolveMemoryPolicyEvaluation({evaluationId:String(body.evaluation_id??""),accountId:session.account_id,outcome:body.outcome==="positive"?"positive":body.outcome==="negative"?"negative":"neutral"})});
    if(body.action==="resolve_incident")return NextResponse.json({incident:await resolveDeploymentIncident({incidentId:String(body.incident_id??""),accountId:session.account_id,userId:session.user_id})});
    return NextResponse.json({error:{code:"action_invalid",message:"A valid execution safety action is required."}},{status:400});
  }catch(error){const message=error instanceof Error?error.message:"execution_action_failed";return NextResponse.json({error:{code:message.split(":")[0],message}},{status:/not_found/.test(message)?404:/required|approval/.test(message)?403:400});}
}
